---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-weatherflow2mqtt
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/home/weatherflow2mqtt/app
  postBuild:
    substituteFrom: []
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  timeout: 5m
  wait: true
  dependsOn:
  - name: home-mosquitto
  - name: networking-multus-config
