---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-weatherflow2mqtt
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/home/weatherflow2mqtt/app
  targetNamespace: home
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: home-mosquitto
  - name: networking-multus-config
