---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radicale
  namespace: web
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/bjw-s/radicale
      tag: 3.1.8

    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      main:
        ports:
          http:
            port: 5232

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hajimari.io/icon: mdi:calendar-export-outline
        hosts:
        - host: &host "radicale.${EXTERNAL_DNS_1_DOMAIN}"
          paths:
          - path: /

    persistence:
      config:
        enabled: true
        type: configMap
        name: radicale
        subPath: config.cfg
        mountPath: /config/config
        readOnly: true

      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/docker/radicale
        mountPath: /data
        readOnly: false

      auth:
        enabled: true
        type: secret
        name: radicale-secret
        subPath: USERS
        mountPath: /config/users
        readOnly: true

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        memory: 79M

    podSecurityContext:
      runAsUser: 1022
      runAsGroup: 1022
      fsGroup: 1022
      fsGroupChangePolicy: "OnRootMismatch"
