---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radicale
  namespace: web
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: tomsquest/docker-radicale
      tag: 3.1.8.3@sha256:b5dac16dafcb003520a1ea95d3e25a24d0955cc552b0d6d447163f0e070780ff
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
    service:
      main:
        ports:
          http:
            port: 5232
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hajimari.io/icon: mdi:calendar-export-outline
        hosts:
        - host: &host "radicale.${EXTERNAL_DNS_1_DOMAIN}"
          paths:
          - path: /
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: config.cfg
        mountPath: /config/config
        readOnly: true
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/docker/radicale
        mountPath: /data
        readOnly: false
      auth:
        enabled: true
        type: secret
        name: *app
        subPath: USERS
        mountPath: /config/users
        readOnly: true
    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        memory: 79M
