---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
- ./secret-radicale.sops.yaml
- ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: radicale
  app.kubernetes.io/instance: radicale
configMapGenerator:
- name: radicale
  files:
  - config/config.cfg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
metadata:
  namespace: web
