apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: web
stringData:
    USERS: ENC[AES256_GCM,data:QlChCwzaR4CEWvyna5WOVluA+Kjojre4b5DbTs0gfhdbwTn2AJQj3dFw,iv:RF1ZCuauos65agLmmwjHYuiNe4Lnpzki+jpcEsVUeQk=,tag:rrpkWeNs/DXECA+fklXMJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bHErRUlCWFZsZzcxVThH
            cE1ZM2N3OXJuVGp1TjRDUisvVEV6UTBxTUdjCis1SVJacm10bnNPYmZqRVlnUUxY
            Z3JGSnRjc0EzbWp3cmRxVEFlNUJtMEUKLS0tIENCZkpjTFR3QVlaeVJJY0pvaVd1
            VTlyeTFvY004cHJPbTZzaUM3YzA3VTAK+iPhg91t7AcUKuTf79cVK2M1tttoK4No
            M8JBPAtN1oWfNZJeCA6WM5Jg+IskZ32oLQof8vQ2HVo9OG6iz61mLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T16:27:55Z"
    mac: ENC[AES256_GCM,data:GWelOqGMBIQNFu6lIOkJ8PfIQqzVfESomMk/Dp0nI4PaWFh1k0tWYKCPueFyEeQxDbgXoFl+VVOsLPJHMGiYr7OlOHbr8gfSQGPUxStHNuUBrjSTQq78Gw8NJzxfTAhcPm0jaCUrNKPlfTDcntLBy55x6IT7sl5wxWd93RtYwOU=,iv:NqWi3F/Jk1bAIRlfDN+ptz9ks6GoEC1mRKyRGaWKd/E=,tag:tGhVLuhQxeXrx6HaSoeg/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
