apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: web
stringData:
    USERS: ENC[AES256_GCM,data:XbzUOpiuPI3MU0gBlZRg8yUZM+7/kxJkErcI+K+xG1IG9ronhEWeDyI=,iv:O4euzRQKiWPaWo05LHmhPkv6y9KtD4GcnQfxIUY65NY=,tag:MqkNJI9aNTKNR3679yojQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bHErRUlCWFZsZzcxVThH
            cE1ZM2N3OXJuVGp1TjRDUisvVEV6UTBxTUdjCis1SVJacm10bnNPYmZqRVlnUUxY
            Z3JGSnRjc0EzbWp3cmRxVEFlNUJtMEUKLS0tIENCZkpjTFR3QVlaeVJJY0pvaVd1
            VTlyeTFvY004cHJPbTZzaUM3YzA3VTAK+iPhg91t7AcUKuTf79cVK2M1tttoK4No
            M8JBPAtN1oWfNZJeCA6WM5Jg+IskZ32oLQof8vQ2HVo9OG6iz61mLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T16:56:28Z"
    mac: ENC[AES256_GCM,data:Ex6pnZGH1FZDqwyzgrricUl6tT7x3EeqiSg6aWTh6sMOUcFHJx3Q+qmnwJb54kJYGU+a4csfxL1R/jTHP9X9xN+1VNiZIn7yByDmsZ5Vpfkq0pAHMNrCtdJZXJHnYi90tewSMQHyH7Q3C8dFGcQ98t8iKROXIHWs1Bg2AqbsogU=,iv:It1ahaV5XwlqUl8FheWKTb+mk/pQjFd3vy3/iic7nIk=,tag:DJS+lfXX3QDsQuwQmJ0OPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
