apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: web
stringData:
    USERS: ENC[AES256_GCM,data:R/Yuy78WuoxsyuQ1oqqwczdgCjq3+JTDOlFzhq/EIefYg/+/ZghGUjCeIqzq4XR0HQrp9agIjdDsGU8JuHVzBYbi4nLaGS1I1tgEL6nklGjeSiUGvgyWH1bvrgr5Ltc=,iv:ayEGpatORoIhUiQmgMoTKsNdszh2rgs8ptQQIHrVR3M=,tag:KISKuE6HQMBHm/jDUgqmnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bHErRUlCWFZsZzcxVThH
            cE1ZM2N3OXJuVGp1TjRDUisvVEV6UTBxTUdjCis1SVJacm10bnNPYmZqRVlnUUxY
            Z3JGSnRjc0EzbWp3cmRxVEFlNUJtMEUKLS0tIENCZkpjTFR3QVlaeVJJY0pvaVd1
            VTlyeTFvY004cHJPbTZzaUM3YzA3VTAK+iPhg91t7AcUKuTf79cVK2M1tttoK4No
            M8JBPAtN1oWfNZJeCA6WM5Jg+IskZ32oLQof8vQ2HVo9OG6iz61mLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T17:12:36Z"
    mac: ENC[AES256_GCM,data:7FzsJCpXJhl+y/fUm8MlaR6Gvg+OVCZPZu3R5YmOaJDpId7mXBWcZmb3uLXMg75pjG8dP2XRtAfTY/I3nOp8W5kLtUj8cop21dB/GHfu7LT6sznqlOUca9r+b2vWIckDPONRJHDiuBiKj5lf53xlc5bS6xnvsGZefKGyKjgS5YQ=,iv:Sx6RS20zT2oRwbxnzjxj4GfIsEeKR7xgUO+wyVC9l6g=,tag:vkC38MrQw21GrWeW3Li5lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
