---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvr-frigate-secret
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "false"
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/nvr/frigate/secret
  targetNamespace: nvr
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvr-frigate-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/nvr/frigate/app
  targetNamespace: nvr
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: frigate
      VOLSYNC_CLAIM: frigate-data
      VOLSYNC_CAPACITY: 4Gi
    substituteFrom: []
  dependsOn:
  - name: nvr-frigate-secret
  - name: storage-rook-ceph
  - name: system-node-feature-discovery-rules
  - name: system-intel-device-plugins-gpu
  - name: nvr-wyze-bridge
