---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-common-mounts
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/common/mounts"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-common
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/common/resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: system-reflector
