---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- ./helmrelease.yaml
configMapGenerator:
- name: node-exporter-grafana-dashboards
  files:
  - ./dashboards/node-exporter.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana.io/folder: Nodes
  labels:
    grafana.io/dashboard: "true"
