---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-mosquitto
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/home/mosquitto/app
  targetNamespace: home
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: mosquitto
      VOLSYNC_CLAIM: mosquitto-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom: []
  dependsOn:
  - name: storage-rook-ceph
