---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpackerr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          *app :
            image:
              repository: docker.io/golift/unpackerr
              tag: unstable
            env:
              TZ: America/New_York
              UN_INTERVAL: 1m
              UN_WEBSERVER_METRICS: "true"
              UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local:8989
              UN_SONARR_0_PATHS_0: /media/downloads/rdt/tv
              UN_SONARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: SONARR_API_KEY
              UN_RADARR_0_URL: http://radarr.media.svc.cluster.local:7878
              UN_RADARR_0_PATHS_0: /media/downloads/rdt/movies
              UN_RADARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: RADARR_API_KEY
              UN_LIDARR_0_URL: http://lidarr.media.svc.cluster.local:8686
              UN_LIDARR_0_PATHS_0: /media/downloads/rdt/music
              UN_LIDARR_0_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: LIDARR_API_KEY
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            resources:
              requests:
                memory: 250Mi
                cpu: 10m
              limits:
                memory: 1024Mi

    service:
      *app :
        controller: *app
        ports:
          http:
            port: 5656

    persistence:
      media:
        existingClaim: nfs-media
        advancedMounts:
          *app :
            *app :
            - path: /media
