---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/haveagitgat/tdarr_acc
      tag: 2.00.20.1

    env:
      TZ: "America/New_York"
      #PUID: "568"
      #PGID: "568"
      ffmpegPath: "/usr/local/bin/ffmpeg"
      TDARR_INSTANCE_NAME: Tdarr
      TDARR__PORT: &port 8265
      TDARR__APPLICATION_URL: &host "tdarr.${EXTERNAL_DNS_1_DOMAIN}"
      TDARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: *port
          server:
            enabled: true
            protocol: TCP
            port: 8266

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "clarity:media-changer-solid"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: *host
          paths:
          - path: /
            pathType: Prefix

    persistence:
      config:
        enabled: true
        existingClaim: tdarr-config
        mountPath: /app/configs
      data:
        enabled: true
        existingClaim: tdarr-data
        mountPath: /app/server
      cache:
        enabled: true
        existingClaim: tdarr-cache
      media:
        enabled: true
        existingClaim: nfs-media
      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/tdarr
        mountPath: /app/server/Tdarr/Backups
        readOnly: false
      nvr:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/batcave-nvr/recordings
        mountPath: /nvr
        readOnly: false

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 100
      supplementalGroups:
      - 34
      - 100
      fsGroupChangePolicy: "OnRootMismatch"
      capabilities:
        add:
        - CHOWN

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
