---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-vector-aggregator
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/vector2/aggregator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: monitoring-loki
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: monitoring-vector-agent
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: "./kubernetes/apps/monitoring/vector2/agent"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-home-ops
#   wait: true
#   postBuild:
#     substituteFrom: []
#   dependsOn:
#   - name: monitoring-vector-aggregator
