---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: ha-fpp-mqtt
  app.kubernetes.io/instance: ha-fpp-mqtt
resources:
- ./secret-ha-fpp-mqtt.sops.yaml
- ./helmrelease.yaml
