---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvr-double-take-secrets
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "false"
spec:
  interval: 10m
  path: "./kubernetes/apps/nvr/double-take/secret"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvr-double-take
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/nvr/double-take/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom:
    - kind: Secret
      name: flux-double-take-secret
      optional: false
  dependsOn:
  - name: nvr-double-take-secrets
  - name: home-mosquitto
  - name: nvr-frigate
  - name: storage-rook-ceph
  # - name: nvr-deepstack
  - name: nvr-compreface
