---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-photoprism-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/photoprism/secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-photoprism-mariadb
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/photoprism/mariadb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom:
    - kind: Secret
      name: photoprism-secrets
      optional: false
  decryption:
    provider: sops
  dependsOn:
  - name: media-photoprism-secrets
  - name: storage-rook-ceph-cluster
  - name: storage-volsync
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-photoprism-cvd-app
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/photoprism/app-cvd"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom:
    - kind: Secret
      name: photoprism-secrets
      optional: false
  decryption:
    provider: sops
  dependsOn:
  - name: storage-rook-ceph-cluster
  - name: media-photoprism-mariadb
