---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: temporal-temporal-secrets
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  path: ./kubernetes/apps/temporal/temporal/secrets
  targetNamespace: temporal
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: temporal-temporal-database
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  path: ./kubernetes/apps/temporal/temporal/database
  targetNamespace: temporal
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: temporal-database
      VOLSYNC_CLAIM: temporal-database-data
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom:
    - kind: Secret
      name: temporal-database-secrets
      optional: false
  dependsOn:
  - name: temporal-temporal-secrets
  - name: storage-rook-ceph-cluster
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: temporal-temporal-server
#   namespace: flux-system
# spec:
#   interval: 10m
#   timeout: 3m
#   retryInterval: 2m
#   path: ./kubernetes/apps/temporal/temporal/server
#   targetNamespace: temporal
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-home-ops
#   postBuild:
#     substituteFrom: []
#   dependsOn:
#   - name: temporal-temporal-database
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: temporal-temporal-ui
#   namespace: flux-system
# spec:
#   interval: 10m
#   timeout: 3m
#   retryInterval: 2m
#   path: ./kubernetes/apps/temporal/temporal/ui
#   targetNamespace: temporal
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-home-ops
#   postBuild:
#     substituteFrom: []
#   dependsOn:
#   - name: temporal-temporal-server
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: temporal-temporal-admin-tools
#   namespace: flux-system
# spec:
#   interval: 10m
#   timeout: 3m
#   retryInterval: 2m
#   path: ./kubernetes/apps/temporal/temporal/admin-tools
#   targetNamespace: temporal
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-home-ops
#   postBuild:
#     substituteFrom: []
#   dependsOn:
#   - name: temporal-temporal-server
