---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-docker
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: drone-runner-docker
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
  values:
    replicaCount: 3
    image:
      repository: drone/drone-runner-docker
      tag: 1.8.3
    podAnnotations:
      reloader.stakater.com/search: "true"
    dind:
      repository: docker
      tag: 20-dind
    env:
      DRONE_RPC_HOST: drone:8080
      DRONE_RPC_PROTO: http
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
  valuesFrom:
  - kind: Secret
    name: drone-secret
    valuesKey: DRONE_RPC_SECRET
    targetPath: env.DRONE_RPC_SECRET
