---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-docker
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: drone-runner-docker
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
  values:
    replicaCount: 3
    image:
      repository: drone/drone-runner-docker
      tag: 1.8.3
    podAnnotations:
      reloader.stakater.com/search: "true"
    dind:
      repository: docker
      tag: 20-dind
      command:
      - "dockerd"
      commandArgs:
      - "--host"
      - &docker_host "tcp://127.0.0.1:2375"
      - "--mtu=1430"
      securityContext:
        privileged: true
    env:
      DOCKER_HOST: *docker_host
      DRONE_RPC_HOST: drone:8080
      DRONE_RPC_PROTO: http
      DRONE_RUNNER_NETWORK_OPTS: "com.docker.network.driver.mtu:1430"
  valuesFrom:
  - kind: Secret
    name: drone-secret
    valuesKey: DRONE_RPC_SECRET
    targetPath: env.DRONE_RPC_SECRET
