---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant
resources:
- ./secret-deploy-key.sops.yaml
- ./secret-home-assistant.sops.yaml
- ./helmrelease.yaml
patchesStrategicMerge:
- ./patches/codeserver.yaml
