---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-server
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
  - name: immich-typesense

  values:
    controller:
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.81.1

    args:
    - start-server.sh

    env:
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: postgres-immich-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgres-immich-app
            key: password

    envFrom:
    - secretRef:
        name: immich-secret
    - configMapRef:
        name: immich-configmap

    service:
      main:
        ports:
          http:
            port: 3001

    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        mountPath: /usr/src/app/upload

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 65541

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 2048Mi

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: immich-server
