apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: web,home,nvr
stringData:
    AWS_SECRET_ACCESS_KEY_ID: ENC[AES256_GCM,data:Dxry/k7CKr3VGBXtETocJ0FtmEc=,iv:yV1OuXLxJr+aDfuumBxnGalF1e2ASKQnTpS9zASugZQ=,tag:GzS2Y+QRi7bXmOX2gtWplg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PEf7N/LqHLMLDcXMuW0pN/eOzvKD+sQTDn1iomBMtH+9THxCWg9S8w==,iv:HTpmjnVmOlXinGb7+a+XSWTx6EqXCyxC9jqW40GtAYM=,tag:4Rx18BETdtLB3pnK+rGNwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMjhpUkJhZm5XenRmRGI3
            NkNwM0drQVBGOElXeWIzVEh5dzE1ejRJRXdnCjlqZHRFRjg3bVpLYXBPMzNqSTcy
            T3RwQ2RSSDhNRUtlREtqUkJCYnYyUGcKLS0tIEp6WE9KMXNwOUVBQ2syT0RFTU9y
            ZDBrRnhYdENCc3pDMldVeEJ1ekVWWDQKJ/8TwdMFLq92P5XtsRUzeE1F6GDKsdA1
            glVH8jh/EubJ0QZ4NK3WvZ+83/BLp1kuqeBKyv4xXhac5kpdqEN6Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T05:39:00Z"
    mac: ENC[AES256_GCM,data:d6aIUupNiFg0HT3vrR6FmNfVY7jnXQBfBZ+/b9ajbkgqAJFdwleFQyEiR/brMtLjkbR8izKE4SlbvrgDPx4Sl7HrJ2Rn5YNLjV1cBB9EbcwIE2cf7sTzIzJWVRUrLoj9qURwb5p9lWQnt4+ytSZ4ILG+733FLuinMW+GPoDnAA8=,iv:WTxG/EBoXIUXk/VzN55RDDfLWX0FPK1OJgeRhPOJQYk=,tag:e+iwRXdHkhSXXLNgr7GUvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
