apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: web,home,nvr
stringData:
    AWS_SECRET_ACCESS_KEY_ID: ENC[AES256_GCM,data:IEok7//tHJPHODYIwhujF//oKjA=,iv:QWlFDtwQoq6SfGkc0s3/OrnDyCcfXkvqxOMuK+073/I=,tag:cUBfZ45VVzIs36bWxLVI9g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MnM1+j0BJBDHvzUjmzol9JrWywmAdujA7K7xCN3XPZyzeBGmmwsJNQ==,iv:B3Gytj5is3elsiUsGIZNWZigbZ2ADozHhDx7nbV6QaU=,tag:SL1m5kiSMz2NhWsgAzkYwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY3htUlJzbmZNcmg5TDNo
            Q0hxRFVWbVVRa1VEWXUwMU93ZnRLNy8wUFVJCkEwWG9wQXZzRDBPSnd0bTkxc0lQ
            QW1NNFhna0hkalFHN1V2aWllbFo2WFkKLS0tIEsvOFV0eER3WktDaW43NnZaUFFD
            VmFTL3dubXY3VmZyTE0wdHpabFo4bm8KEgPTQ7V5cvkKMGT0+u94FS0PdWMDZJiR
            IYxSIDlS6rrt+Id4xw3ycAQhv4dBewqRkSkS+Rj7ykY/97gmCzH4ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T19:52:14Z"
    mac: ENC[AES256_GCM,data:9Ow7wlAW5qabF1q2m2+fgx2AKxZh4j/6IFmXhrMIZm82jI5keeqsyUUqG0QofmZKLKcN+uE6cVwndxsE6zMonGeZ7N/feJ2ajaNk2nsAw4+kTEDHrqIxNU6JmpqDdr4udYiuzcM9/MuhxWR7/KMERRqcTYIBl24dmRLcQDfS0w0=,iv:tjbrBy2bOdug/uxeie1RQu+I5hGURcla8OLzNuwG0WM=,tag:FHV54c7KQYuQ//o3ni72MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
