apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: web,home,nvr
stringData:
    AWS_SECRET_ACCESS_KEY_ID: ENC[AES256_GCM,data:IEok7//tHJPHODYIwhujF//oKjA=,iv:QWlFDtwQoq6SfGkc0s3/OrnDyCcfXkvqxOMuK+073/I=,tag:cUBfZ45VVzIs36bWxLVI9g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MnM1+j0BJBDHvzUjmzol9JrWywmAdujA7K7xCN3XPZyzeBGmmwsJNQ==,iv:B3Gytj5is3elsiUsGIZNWZigbZ2ADozHhDx7nbV6QaU=,tag:SL1m5kiSMz2NhWsgAzkYwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY3htUlJzbmZNcmg5TDNo
            Q0hxRFVWbVVRa1VEWXUwMU93ZnRLNy8wUFVJCkEwWG9wQXZzRDBPSnd0bTkxc0lQ
            QW1NNFhna0hkalFHN1V2aWllbFo2WFkKLS0tIEsvOFV0eER3WktDaW43NnZaUFFD
            VmFTL3dubXY3VmZyTE0wdHpabFo4bm8KEgPTQ7V5cvkKMGT0+u94FS0PdWMDZJiR
            IYxSIDlS6rrt+Id4xw3ycAQhv4dBewqRkSkS+Rj7ykY/97gmCzH4ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T20:49:52Z"
    mac: ENC[AES256_GCM,data:pFGFqs1+w2udxWjfkG0ve1FZm1iUGpxSoutnB3xHvcqxh1EyNTnuznVxNfi8pS8Gv5GL3j0jQ0jb7WUdNRC4PHEeK/o0ZmQuyYsM2SueDgNo7FR8vOBBaBfxrxXRuqdELd1oCMlSed5aeDEXRRIhoffT0u3UvOg2blqoF+NrqnU=,iv:p+TPdUC6RW5np9HNsHaJ1dQE8oufio/Yripw/XNlzrg=,tag:phESWtG+xtokaeNaMNYVNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
