---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- ./helmrelease.yaml
- ./dashboard
configMapGenerator:
- name: overseerr-grafana-dashboards
  files:
  - ./dashboards/overseerr.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana.io/folder: Media
  labels:
    grafana.io/dashboard: "true"
commonLabels:
  app.kubernetes.io/name: overseerr
  app.kubernetes.io/instance: overseerr
