---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-temporal-database
  namespace: flux-system
spec:
  path: ./kubernetes/apps/web/temporal/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
  - name: databases-cloudnative-pg
  - name: storage-rook-ceph-cluster
