---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crunchydata
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry.developers.crunchydata.com/crunchydata
  timeout: 3m
