---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-ollama
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/ai/ollama/app
  targetNamespace: ai
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: ollama
      VOLSYNC_CLAIM: ollama-data
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom: []
  dependsOn:
  - name: storage-rook-ceph-cluster
  - name: storage-volsync
