---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./helmrelease.yaml
- ../../../../templates/volsync
configMapGenerator:
- name: frigate-config
  files:
  - config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/name: frigate
  app.kubernetes.io/instance: frigate
