---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvr
resources:
- ./helmrelease.yaml
- ./volsync.yaml
configMapGenerator:
- name: frigate-configmap
  files:
  - config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/name: frigate
  app.kubernetes.io/instance: frigate
