---
apiVersion: v1
kind: Secret
metadata:
  name: frigate-volsync-secret
  namespace: nvr
spec:
stringData:
  RESTIC_REPOSITORY: s3:http://${MINIO_S3_URL}/${VOLSYNC_S3_BUCKET_NAME}/frigate
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_S3_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_S3_SECRET_ACCESS_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: frigate
  namespace: nvr
spec:
  sourcePVC: database-frigate-0
  trigger:
    schedule: "0 */3 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: frigate-volsync-secret
    cacheCapacity: 4Gi
    volumeSnapshotClassName: ceph-block
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
