---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-microservices
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
  - name: immich-server
  - name: immich-typesense

  values:
    controller:
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.94.1

    args:
    - start-microservices.sh

    env:
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: postgres-immich-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgres-immich-app
            key: password

    envFrom:
    - secretRef:
        name: immich-secret
    - configMapRef:
        name: immich-configmap

    service:
      main:
        enabled: false

    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        mountPath: /usr/src/app/upload
      geocoding-dump:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/.reverse-geocoding-dump
      geoname-dump:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/node_modules/local-reverse-geocoder/geonames_dump

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 44
      - 109
      - 65541

    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 512Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 8000Mi

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: immich-microservices
