---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.0.2@sha256:0e62d048aa0baba4bd7d2f897a2d3618bbd2ffe8616ef728bf751af999c78537

    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.media,
        sabnzbd.media.svc,
        sabnzbd.media.svc.cluster,
        sabnzbd.media.svc.cluster.local,
        sabnzbd.${EXTERNAL_DNS_1_DOMAIN}
      SABNZBD__API_KEY:
        valueFrom:
          secretKeyRef:
            name: starr-apps-secret
            key: SABNZBD_API_KEY
      SABNZBD__NZB_KEY:
        valueFrom:
          secretKeyRef:
            name: starr-apps-secret
            key: SABNZBD_NZB_KEY

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:download-circle-outline"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host sabnzbd.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    persistence:
      media:
        enabled: true
        existingClaim: nfs-media
        mountPath: /data/media

      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/sabnzbd
        mountPath: /backups
        readOnly: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 65539

    resources:
      requests:
        cpu: 5m
        memory: "2392M"
      limits:
        memory: "2392M"
