apiVersion: v1
kind: Secret
metadata:
    name: flux-porla-secret
    namespace: flux-system
stringData:
    PORLA_SECRET_KEY: ENC[AES256_GCM,data:lU07WyuS0mlEyrMdlawStKgOq6RCmedRFNcN2/8ERlY=,iv:YZKSulawQNHFVm6VGfCtkaeJyKy6IEwpa5g5qeoNiLg=,tag:wniGrc6XC4B3pb7VV7M6EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS29pdXRzVUthdzVRY21Q
            bTAzY0U2SHNVbEJsZVhtWEVCTnRzUEg5cHc0CmdUSHExMXdHR0x3OTQ2QzNZU0Q0
            cGRkdGVMSFBrSjNZc2VIQmo5S1BJVWMKLS0tIGhhdWhIUVpaSTVrQzd0N3hWc1RR
            Qk9pZVJWS3FZVWNwVFVPY0g5b3RsYzQKayh6PETmTnR8Uw48sdoq37+nhFHoT3lS
            NhbrTZ6JC4vtWdaW6FQWhFIvH3paruppFZDbs5oM4ImxxRcnYakpLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T20:51:12Z"
    mac: ENC[AES256_GCM,data:WOBWq0Rd7ZqVgHod+Ho40BWC+s0yO1LvUEBP8ab2GTJ6iGkgGyYLZFNJ9l48jPMELBhbRCQ6ruI7uS+8xlzYRbY5YH7D/H/GLWA5o+VxX8yTCiTNHce2FRC+2VRdlnb/M5XDAQFNYT3uu+gWntHv84ntxxoW3gQukIF5T9LYnUQ=,iv:j5YjEbGXX2E8IPx0dcBjBzJvhzJJrl13yMtZOaeP+Hk=,tag:Jron0vtiNqMChzr9rksy5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
