---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tautulli
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
            - 65539
            - 1030

        containers:
          *app :
            image:
              repository: ghcr.io/onedr0p/tautulli
              tag: 2.15.1@sha256:cf198fe0ee64336e9e1212c162f25b6370e5e04659ec51d934aac24cb0c408bc
            env:
              TZ: America/New_York
              TAUTULLI__PORT: &port 8181
            resources:
              requests:
                memory: 350Mi
                cpu: 5m
              limits:
                memory: 431Mi

    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      *app :
        className: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:chart-bar"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host tautulli.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: *app
              port: *port

    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
        - path: /config

      backups:
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/tautulli
        advancedMounts:
          *app :
            *app :
            - path: /config/backup
              readOnly: false

    serviceMonitor:
      metrics:
        serviceName: *app
        endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 10m
          scrapeTimeout: 10s
