---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-sabnzbd
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/downloads/sabnzbd/app
  targetNamespace: downloads
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: sabnzbd
      VOLSYNC_CLAIM: sabnzbd-data
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom: []
  dependsOn:
  - name: monitoring-kube-prometheus-stack-crds
  - name: networking-pod-gateway
  - name: ingress-ingress-nginx
