---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-mariadb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts/mariadb
  timeout: 3m
