mqtt:
  host: ${FRIGATE_MQTT_HOST}
  port: ${FRIGATE_MQTT_PORT}
  topic_prefix: frigate
  client_id: frigate
  user: ${FRIGATE_MQTT_USERNAME}
  password: ${FRIGATE_MQTT_PASSWORD}

logger:
  default: info
  logs:
    frigate.record: debug

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50 # 10 x fps
    max_frames:
      default: 3000
      objects:
        person: 300

ffmpeg:
  hwaccel_args:
  - -hwaccel
  - vaapi
  - -hwaccel_device
  - /dev/dri/renderD128
  - -hwaccel_output_format
  - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -f flv -c:a aac

motion:
  improve_contrast: true

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 10

record:
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 14
      mode: active_objects

rtmp:
  enabled: false

go2rtc:
  streams:
    backyard:
    - ${FRIGATE_CAMERA_BACKYARD_HOST}
    driveway:
    - ${FRIGATE_CAMERA_DRIVEWAY_HOST}
    front_doorbell:
    - ${FRIGATE_CAMERA_FRONT_DOORBELL_HOST}
    garage:
    - ${FRIGATE_CAMERA_GARAGE_HOST}
    great_room:
    - ${FRIGATE_CAMERA_GREAT_ROOM_HOST}
    kitchen:
    - ${FRIGATE_CAMERA_KITCHEN_HOST}
    - "ffmpeg:rtsp_cam#audio=opus"
    patio:
    - ${FRIGATE_CAMERA_PATIO_HOST}
    pennys_room:
    - ${FRIGATE_CAMERA_PENNYS_ROOM_HOST}
    sadies_room:
    - ${FRIGATE_CAMERA_SADIES_ROOM_HOST}
    side_left:
    - ${FRIGATE_CAMERA_SIDE_LEFT_HOST}
    side_right:
    - ${FRIGATE_CAMERA_SIDE_RIGHT_HOST}
  webrtc:
    candidates:
    - ${SERVICE_ADDRESS_FRIGATE}:8555

cameras:

  backyard:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_BACKYARD_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      filters:
        person:
          min_area: 25800
    motion:
      mask:
      - 0,131,265,86,669,39,683,74,1063,137,1718,315,1920,400,1920,0,0,0

  driveway:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_DRIVEWAY_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      - car
      filters:
        person:
          min_area: 14000
    motion:
      mask:
      - 181,662,93,348,270,267,372,243,535,230,816,222,1067,228,1379,249,1734,298,1920,330,1920,0,0,0,0,762

  front_doorbell:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_FRONT_DOORBELL_HOST}
        roles:
        - detect
    detect:
      width: 1600
      height: 1200
    objects:
      track:
      - person
      filters:
        person:
          min_area: 4500
    motion:
      mask:
      - 1360,0,1047,206,1073,522,1071,893,872,745,865,422,615,401,615,679,635,1200,0,1200,0,0
    zones:
      at_front_door:
        coordinates: 1060,808,1600,1121,1600,1200,635,1200,625,894

  garage:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_GARAGE_HOST}
        roles:
        - detect
        - car
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
      filters:
        person:
          min_area: 50000

  great_room:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_GREAT_ROOM_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
    motion:
      mask:
      - 1048,248,1081,524,623,732,551,389
      - 63,250,942,69,1058,210,1529,250,1921,200,2560,0,0,0,0,608

  kitchen:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_KITCHEN_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
      filters:
        person:
          min_area: 32000
    motion:
      mask:
      - 923,330,1637,492,2560,414,2560,0,0,0,0,339

  patio:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_PATIO_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
    motion:
      mask:
      - 175,999,1599,570,2303,959,2560,517,2560,0,0,0

  pennys_room:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_PENNYS_ROOM_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440

  sadies_room:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_SADIES_ROOM_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
      filters:
        person:
          min_area: 65000

  side_left:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_SIDE_LEFT_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      filters:
        person:
          min_area: 8000
    motion:
      mask:
      - 0,394,305,274,575,191,936,109,1227,64,1546,44,1777,89,1920,1080,1920,0,0,0

  side_right:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_SIDE_RIGHT_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      filters:
        person:
          min_area: 125000
          max_area: 340000
    motion:
      mask:
      - 0,702,318,322,680,74,998,50,1100,0,1920,390,1920,0,0,0
