mqtt:
  host: ${FRIGATE_MQTT_HOST}
  port: ${FRIGATE_MQTT_PORT}
  topic_prefix: frigate
  client_id: frigate
  user: ${FRIGATE_MQTT_USERNAME}
  password: ${FRIGATE_MQTT_PASSWORD}

logger:
  default: info
  logs:
    frigate.record: debug

# 4GB volume atm
database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50 # 10 x fps
    max_frames:
      default: 3000
      objects:
        person: 300

ffmpeg:
  hwaccel_args:
  - -hwaccel
  - vaapi
  - -hwaccel_device
  - /dev/dri/renderD128
  - -hwaccel_output_format
  - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

motion:
  improve_contrast: true

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 10

record:
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 14
      mode: active_objects

go2rtc:
  streams:
    backyard:
    - ${FRIGATE_CAMERA_BACKYARD_HOST}
    bambu_x1_carbon:
    - ${FRIGATE_CAMERA_BAMBU_X1_CARBON_HOST}
    driveway:
    - ${FRIGATE_CAMERA_DRIVEWAY_HOST}
    front_doorbell:
    - ${FRIGATE_CAMERA_FRONT_DOORBELL_HOST}
    garage:
    - ${FRIGATE_CAMERA_GARAGE_HOST}
    - "ffmpeg:garage#audio=opus"
    great_room:
    - ${FRIGATE_CAMERA_GREAT_ROOM_HOST}
    - "ffmpeg:great_room#audio=opus"
    kitchen:
    - ${FRIGATE_CAMERA_KITCHEN_HOST}
    - "ffmpeg:kitchen#audio=opus"
    # mobile_cam:
    # - ${FRIGATE_CAMERA_MOBILE_CAM_HOST}
    # - "ffmpeg:mobile_cam"
    patio:
    - ${FRIGATE_CAMERA_PATIO_HOST}
    - "ffmpeg:patio#audio=opus"
    pennys_room:
    - ${FRIGATE_CAMERA_PENNYS_ROOM_HOST}
    - "ffmpeg:pennys_room#audio=opus"
    # prusa_i3_mk3s_plus:
    # - ${FRIGATE_CAMERA_PRUSA_I3_MK3S_PLUS_HOST}
    # - "ffmpeg:prusa_i3_mk3s_plus"
    sadies_room:
    - ${FRIGATE_CAMERA_SADIES_ROOM_HOST}
    - "ffmpeg:sadies_room#audio=opus"
    side_left:
    - ${FRIGATE_CAMERA_SIDE_LEFT_HOST}
    side_right:
    - ${FRIGATE_CAMERA_SIDE_RIGHT_HOST}
  webrtc:
    candidates:
    - ${SERVICE_ADDRESS_FRIGATE}:8555

cameras:

  backyard:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_BACKYARD_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      filters:
        person:
          min_area: 25800
    mqtt: &cameraMQTTSettings
      enabled: true
      timestamp: true
      bounding_box: false
      crop: true
      height: 500
      quality: 100

  bambu_x1_carbon:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_BAMBU_X1_CARBON_HOST}
        roles:
        - detect
    detect:
      width: 1280
      height: 720
    mqtt: *cameraMQTTSettings

  driveway:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_DRIVEWAY_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      - car
      filters:
        person:
          min_area: 14000
    mqtt: *cameraMQTTSettings

  front_doorbell:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_FRONT_DOORBELL_HOST}
        roles:
        - detect
    detect:
      width: 1600
      height: 1200
    objects:
      track:
      - person
      filters:
        person:
          min_area: 4500
    mqtt: *cameraMQTTSettings

  garage:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_GARAGE_HOST}
        roles:
        - detect
        - car
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
      filters:
        person:
          min_area: 50000
    mqtt: *cameraMQTTSettings

  great_room:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_GREAT_ROOM_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
    mqtt: *cameraMQTTSettings

  kitchen:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_KITCHEN_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
      filters:
        person:
          min_area: 32000
    mqtt: *cameraMQTTSettings

  # mobile_cam:
  #   ffmpeg:
  #     inputs:
  #     - path: ${FRIGATE_CAMERA_MOBILE_CAM_HOST}
  #       roles:
  #       - detect
  #   detect:
  #     width: 1920
  #     height: 1080
  #   mqtt: *cameraMQTTSettings

  patio:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_PATIO_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
    mqtt: *cameraMQTTSettings

  pennys_room:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_PENNYS_ROOM_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    mqtt: *cameraMQTTSettings

  # prusa_i3_mk3s_plus:
  #   ffmpeg:
  #     inputs:
  #     - path: ${FRIGATE_CAMERA_PRUSA_I3_MK3S_PLUS_HOST}
  #       roles:
  #       - detect
  #   detect:
  #     width: 1920
  #     height: 1080
  #   mqtt: *cameraMQTTSettings

  sadies_room:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_SADIES_ROOM_HOST}
        roles:
        - detect
    detect:
      width: 2560
      height: 1440
    objects:
      track:
      - person
      filters:
        person:
          min_area: 65000
    mqtt: *cameraMQTTSettings

  side_left:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_SIDE_LEFT_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      filters:
        person:
          min_area: 8000
    mqtt: *cameraMQTTSettings

  side_right:
    ffmpeg:
      inputs:
      - path: ${FRIGATE_CAMERA_SIDE_RIGHT_HOST}
        roles:
        - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track:
      - person
      filters:
        person:
          min_area: 125000
          max_area: 340000
    mqtt: *cameraMQTTSettings
