---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app actions-runner-controller
  namespace: &namespace actions-runner-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  targetNamespace: *namespace
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app actions-runner-controller-runners
  namespace: &namespace actions-runner-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: storage-rook-ceph-cluster
    - name: actions-runner-controller
      namespace: *namespace
  interval: 10m
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/runners
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  targetNamespace: *namespace
  timeout: 3m
  wait: true
