---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-system-actions-runner-controller
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  commonMetadata:
    labels:
      app.kubernetes.io/name: actions-runner-controller
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  targetNamespace: actions-runner-system
  wait: true
  postBuild:
    substituteFrom: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-system-actions-runner-controller-runners
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: actions-runner-controller-runners
  dependsOn:
    - name: storage-rook-ceph-cluster
    - name: actions-runner-system-actions-runner-controller
  interval: 10m
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/runners
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  targetNamespace: actions-runner-system
  timeout: 3m
  wait: true
  postBuild:
    substituteFrom: []
