---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: games-ffxi-secrets
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/games/ffxi/secrets
  targetNamespace: games
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: games-ffxi-database
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  path: ./kubernetes/apps/games/ffxi/database
  targetNamespace: games
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: ffxi-database
      VOLSYNC_CLAIM: ffxi-database-data
      VOLSYNC_CAPACITY: 50Gi
    substituteFrom:
      - kind: Secret
        name: ffxi-secrets
        optional: false
  dependsOn:
    - name: games-ffxi-secrets
    - name: storage-rook-ceph-cluster
