---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
- ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: immich-redis
  app.kubernetes.io/instance: immich-redis
  app.kubernetes.io/part-of: immich
