---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: web
data:
  # GENERAL
  LOG_LEVEL: log
  NODE_ENV: "production"

  # GEOCODING
  DISABLE_REVERSE_GEOCODING: "true"

  # URLS
  IMMICH_WEB_URL: http://immich-web.web.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.web.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_ENABLED: "true"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.web.svc.cluster.local:3003
  PUBLIC_IMMICH_SERVER_URL: https://immich.${EXTERNAL_DNS_1_DOMAIN}
  IMMICH_API_URL_EXTERNAL: /api

  # DATABASE
  DB_HOSTNAME: postgres-immich-rw.web.svc.cluster.local
  DB_PORT: "5432"
  DB_DATABASE_NAME: immich

  # REDIS
  REDIS_HOSTNAME: immich-redis.web.svc.cluster.local
  REDIS_PORT: "6379"

  # TYPESENSE
  TYPESENSE_HOST: immich-typesense.web.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config

  # MACHINE LEARNING
  MACHINE_LEARNING_CACHE_FOLDER: /cache
  TRANSFORMERS_CACHE: /cache
