---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-immich
  namespace: web
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.5-8

  # let k8s handle upgrades
  primaryUpdateStrategy: unsupervised

  # prefer downtime of image download from registry instead of switching primary instance (promote a standby instance to primary) when current primary pod is updated
  primaryUpdateMethod: restart

  storage:
    size: 5Gi
    storageClass: ceph-block
  postgresql:
    parameters:
      # amount of RAM to use for data caching, https://postgresqlco.nf/doc/en/param/shared_buffers/
      shared_buffers: 256MB
  monitoring:
    enablePodMonitor: true

  # configured according to below link to allow customizing of initdb via Flux
  # https://cloudnative-pg.io/documentation/1.20/bootstrap/#configure-the-application-database
  bootstrap:
    initdb:
      dataChecksums: true
      database: immich
      owner: immich
      encoding: "UTF8"
      localeCollate: en_US.utf8
      localeCType: en_US.utf8

  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://immich-postgres/
      endpointURL: http://${MINIO_S3_URL}
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: AWS_SECRET_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-secret
          key: AWS_SECRET_ACCESS_KEY
