apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: web
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:AHvj0xue15Udds986KeSoT5zq3Fth+eh,iv:LM03Kgpc5MLLdv1p8lcuK8FhMwb5/Yd8yMckLAjv1d0=,tag:rH0+4Z61TrVbT7q2rKmYjQ==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:jc3JqpokKcR9wJftdFxjTr9H71xjGtpO,iv:Yzm4KG/+80WOqoIGxVM1SZHQ1bAMzqgxu/197guhQms=,tag:R7nAWbtbHs9DEW5/sfodtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOHdVMGZKcWdjdFVFZGNW
            RTk5cXovTW9pdk9MVi9EOCt0d29iSHEyQ0VnCktGS2pCREZkeGV1YU10WStrTlZP
            SmpKcEZ5cTJQemVnTFh1WU55eE9JSjgKLS0tIFpIbGE4eUl3TnMrcTZvRDJnam0z
            dUxSUUlQK0pKV2hlM3FmeEFlYVFFNG8KjANgqUHKbkxn8TdWE2fBBHpPwOmfm/EO
            BsdilDmL0yXZAvTeSi/Cr0cWmyN4Cki9dwYKbpZYL0gzcT06pBb3hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T06:40:28Z"
    mac: ENC[AES256_GCM,data:OcemHiLpykET9ZWNT01w5XHZ/aNzUsmlLToGWmrUrNYUrlEVTtZNS9HTcNyP16cRuF7hSfWwVCGGCXbduzT1oFG6sWeSoOo4n/+atQGKGA5OpdpEGpmAVLm62D5Pk3icTJE+S6X4ylWbSWBSWLzmjpDWyTpkJCBblZIJfLZ7TOc=,iv:hwrDao492Q+Zi0DX4wOokCqU7WNrkZ3T2tbml885z9o=,tag:SLL7K7tOBVK7UozEvL116A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
