---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./common/ks.yaml
- ./flaresolverr/ks.yaml
- ./prowlarr/ks.yaml
- ./deluge/ks.yaml
- ./porla/ks.yaml
