---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases-cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/databases/cloudnative-pg/app
  targetNamespace: databases
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: monitoring-kube-prometheus-stack-crds
  - name: system-reflector
