---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- ./helmrelease.yaml
configMapGenerator:
- name: recyclarr-configmap
  files:
  - ./config/radarr.yaml
  - ./config/sonarr.yaml
  - ./config/sonarr-anime.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
- pairs:
    app.kubernetes.io/name: recyclarr
    app.kubernetes.io/instance: recyclarr
