---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./helmrelease.yaml
- ../../../../templates/volsync
configMapGenerator:
- name: recyclarr-configmap
  files:
  - ./config/radarr.yml
  - ./config/sonarr.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
- pairs:
    app.kubernetes.io/name: recyclarr
    app.kubernetes.io/instance: recyclarr
