---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./mosquitto/ks.yaml
- ./weatherflow2mqtt/ks.yaml
- ./zigbee2mqtt/ks.yaml
- ./zwavejs2mqtt/ks.yaml
- ./home-assistant/ks.yaml
