---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./helmrelease.yaml
- ../../../../templates/volsync
configMapGenerator:
- name: sonarr-grafana-dashboards
  files:
  - ./dashboards/sonarr.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana.io/folder: Media
  labels:
    grafana.io/dashboard: "true"
commonLabels:
  app.kubernetes.io/name: sonarr
  app.kubernetes.io/instance: sonarr
