---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- ./helmrelease.yaml
configMapGenerator:
- name: sonarr-grafana-dashboards
  files:
  - ./dashboards/sonarr.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana.io/folder: Media
commonLabels:
  app.kubernetes.io/name: sonarr
  app.kubernetes.io/instance: sonarr
