---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- ./pvc.yaml
- ./volsync.yaml
- ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: photoprism
  app.kubernetes.io/instance: photoprism
