---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultwarden-backup
  namespace: web
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vaultwarden-backup
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - /scripts/backup.sh
            envFrom:
            - secretRef:
                name: vaultwarden-backup-secrets
            volumeMounts:
            - mountPath: /scripts
              name: vaultwarden-backup-scripts
            - mountPath: /vaultwarden-data
              name: vaultwarden-data
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 493
              name: vaultwarden-backup-scripts
            name: vaultwarden-backup-scripts
          - nfs:
              server: "${SYNOLOGY_ADDRESS}"
              path: /volume1/docker/vaultwarden
            name: vaultwarden-data