---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
- ./secret-vaultwarden-backups.sops.yaml
- ./cronjob.yaml
configMapGenerator:
- name: vaultwarden-backup-scripts
  files:
  - config/backup.sh
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
