---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-deluge
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/deluge/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: downloads-common-mounts
  - name: system-reflector
  - name: storage-rook-ceph
  - name: monitoring-kube-prometheus-stack-crds
  - name: networking-pod-gateway
