---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    controllers:
       server:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: temporalio/auto-setup
              tag: 1.27.2
            env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: temporal-database-secrets
                  key: db-port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: temporal-database-secrets
                  key: db-username
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: temporal-database-secrets
                  key: postgres-password
            - name: POSTGRES_SEEDS
              valueFrom:
                secretKeyRef:
                  name: temporal-database-secrets
                  key: db-host
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/dev-dynamic-config.yaml

    persistence:
      dynamic-config:
        type: configMap
        name: temporal-dynamic-config
        advancedMounts:
          server:
            app:
            - path: /etc/temporal/config/dynamicconfig

    service:
      main:
        controller: server
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_TEMPORAL_SERVER}
        ports:
          http:
            port: 7233
