---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: temporal
  app.kubernetes.io/instance: temporal
configMapGenerator:
- name: temporal-dynamic-config
  files:
  - files/dev-dynamic-config.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
