---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: double-take
  namespace: nvr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/skrashevich/double-take
      tag: v1.13.11.3

    env:
      TZ: "America/New_York"

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host doubletake.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: &config double-take-config
        mountPath: "/.storage/config/config.yml"
        subPath: "config.yml"

    volumeClaimTemplates:
    - name: storage
      mountPath: /.storage
      accessMode: ReadWriteOnce
      size: 10Gi
      stoageClass: ceph-block

    configMaps:
      config:
        enabled: true
        data:
          config.yml: |-
            mqtt:
              host: mosquitto.home.svc.cluster.local
              username: "${MQTT_USERNAME}"
              password: "${MQTT_PASSWORD}"

            frigate:
              url: http://frigate.nvr.svc.cluster.local:5000
              update_sub_labels: true
              stop_on_match: true
              min_area: 40000

              labels:
              - person

              cameras:
              - backyard
              - driveway
              - garage
              - great_room
              - kitchen
              - patio
              - pennys_room
              - prusa_i3_mk3s_plus
              - sadies_room
              - side_left
              - side_right

              zones:
              - camera: front_doorbell
                zone: at_front_door

              events: {}

            detect:
              match:
                save: true
                min_area: 10000
              unknown:
                save: true

            detectors:
              # deepstack:
              #   url: "http://deepstack.nvr.svc.cluster.local:5000"
              #   key: "${DEEPSTACK_API_KEY}"

              compreface:
                url: "http://compreface.nvr.svc.cluster.local:8000"
                key: "${COMPREFACE_API_KEY}"

            time:
              timezone: America/New_York

            notify: {}

    resources:
      requests:
        cpu: 30m
        memory: 200M
      limits:
        memory: 1Gi

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
