---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvr
resources:
- ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: double-take
  app.kubernetes.io/instance: double-take
