---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  values:
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.17.1
        env:
          TZ: America/New_York
        workingDir: /config
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/icon: "mdi:vs-code"
            hajimari.io/appName: "HASS VSCODE"
            nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
          - host: code.${EXTERNAL_DNS_2_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
        volumeMounts:
        - name: config
          mountPath: /config
