---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-web
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
  - name: immich-server

  values:
    controller:
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.87.0

    command: /bin/sh
    args:
    - ./entrypoint.sh

    env:
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: postgres-immich-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgres-immich-app
            key: password

    envFrom:
    - secretRef:
        name: immich-secret
    - configMapRef:
        name: immich-configmap

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
        - host: &host media.${EXTERNAL_DNS_2_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
          - path: /api
            pathType: Prefix
            service:
              name: immich-server
              port: 3001

    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        mountPath: /usr/src/app/upload

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 65541

    resources:
      requests:
        cpu: 5m
        memory: 64M
      limits:
        memory: 256Mi
