---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-rdt-client
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/downloads/rdt-client/app
  targetNamespace: downloads
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: rdt-client
      VOLSYNC_CLAIM: rdt-client-data
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom: []
  dependsOn:
  - name: storage-rook-ceph-cluster
  - name: networking-pod-gateway
  - name: ingress-ingress-nginx
