---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-rdt-client
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/rdt-client/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: storage-rook-ceph-cluster
  - name: networking-pod-gateway