---
apiVersion: &apiVersion kustomize.toolkit.fluxcd.io/v1
kind: &kind Kustomization
metadata:
  name: media-photoprism-cvd-secrets
  namespace: &namespace flux-system
spec:
  interval: &interval 10m
  timeout: &timeout 3m
  retryInterval: &retryInterval 2m
  path: ./kubernetes/apps/media/photoprism/cvd/secrets
  targetNamespace: &targetNamespace media
  prune: true
  wait: true
  sourceRef: &sourceRef
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn: []
---
apiVersion: *apiVersion
kind: *kind
metadata:
  name: media-photoprism-cvd-mariadb
  namespace: *namespace
spec:
  interval: *interval
  timeout: *timeout
  retryInterval: *retryInterval
  path: ./kubernetes/apps/media/photoprism/cvd/mariadb
  targetNamespace: *targetNamespace
  prune: true
  wait: true
  sourceRef: *sourceRef
  postBuild:
    substitute:
      APP: photoprism-cvd-mariadb
      VOLSYNC_CLAIM: photoprism-cvd-mariadb-data
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom: []
  dependsOn:
  - name: media-photoprism-cvd-secrets
  - name: storage-rook-ceph-cluster
