---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-photoprism-cvd-secrets
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/media/photoprism/cvd/secrets
  targetNamespace: media
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom: []
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-photoprism-cvd-mariadb
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/media/photoprism/cvd/mariadb
  targetNamespace: media
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: photoprism-cvd-mariadb
      VOLSYNC_CLAIM: photoprism-cvd-mariadb-data
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom:
      - kind: Secret
        name: photoprism-cvd-secrets
        optional: false
  dependsOn:
    - name: media-photoprism-cvd-secrets
    - name: storage-rook-ceph-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-photoprism-cvd-app
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/media/photoprism/cvd/app
  targetNamespace: media
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substituteFrom:
      - kind: Secret
        name: photoprism-cvd-secrets
        optional: false
  dependsOn:
    - name: media-photoprism-cvd-mariadb
    - name: ingress-ingress-nginx
