---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-prowlarr
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/downloads/prowlarr/app
  targetNamespace: downloads
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: prowlarr
      VOLSYNC_CLAIM: prowlarr-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom: []
  dependsOn:
  - name: storage-rook-ceph-cluster
  - name: monitoring-kube-prometheus-stack-crds
  - name: networking-pod-gateway
