---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  values:
    env:
      TZ: America/New_York

    hajimari:
      title: Home Ops
      darkTheme: catppuccin-macchiato
      customThemes:
      - name: catppuccin-macchiato
        backgroundColor: "#24273a"
        primaryColor: "#cad3f5"
        accentColor: "#8aadf4"
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: false
      namespaceSelector:
        matchNames:
        - downloads
        - home
        - media
        - monitoring
        - networking
        - nvr
        - storage
        - system

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: "dashboard.${EXTERNAL_DNS_1_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix

    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"

    persistence:
      data:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 100m
        memory: 128M
