---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ffxi-mariadb
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb
      version: 20.5.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.7.2-debian-12-r0
    auth:
      rootPassword: ${MARIADB_FFXI_ROOT_PASSWORD}
      database: ${MARIADB_FFXI_DATABASE}
      username: ${MARIADB_FFXI_USERNAME}
      password: ${MARIADB_FFXI_PASSWORD}
    primary:
      persistence:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_FFXI_DB}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
