---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/dani-garcia/vaultwarden
      tag: 1.34.1

    envFrom:
    - secretRef:
        name: vaultwarden-secret

    env:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://bw.${EXTERNAL_DNS_1_DOMAIN}"

    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            port: 3012

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "simple-icons:bitwarden"
        hosts:
        - host: "bw.${EXTERNAL_DNS_1_DOMAIN}"
          paths:
          - path: /
            service:
              port: 80
          - path: /notifications/hub
            service:
              port: 3012

    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/docker/vaultwarden
        mountPath: /data
        readOnly: false
