---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: snapshot-controller
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # TODO: CHANGE THIS BACK TO REGISTRY.K8S.IO (JUST REMOVE)
    image:
      repository: docker.io/dyrnq/snapshot-controller
      tag: v6.2.2

    serviceMonitor:
      create: true
