---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
- ./helmrelease.yaml
configMapGenerator:
- name: ingress-nginx-dashboards
  files:
  - ./dashboards/nginx-ingress-controller.json
  - ./dashboards/request-handling-performance.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana.io/folder: Ingress
  labels:
    grafana.io/dashboard: "true"
