---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.9.1.3981@sha256:ab99cd7c9ff6724dc2e9ac42ad5d10bed5aeb77cb70ccf02f8f3ce3a787cb7eb

    env:
      TZ: America/New_York
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__AUTHENTICATION_METHOD: External
      PROWLARR__APPLICATION_URL: "https://prowlarr.${EXTERNAL_DNS_1_DOMAIN}"
      PROWLARR__LOG_LEVEL: info
      PROWLARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: starr-apps-secret
            key: PROWLARR_API_KEY

    sidecars:
      exporter:
        name: exporter
        image: ghcr.io/onedr0p/exportarr:v1.5.5
        args:
        - prowlarr
        - --enable-additional-metrics
        env:
        - name: URL
          value: "http://localhost:9696"
        - name: PORT
          value: &metricsPort 9710
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: starr-apps-secret
              key: PROWLARR_API_KEY
        ports:
        - name: metrics
          containerPort: *metricsPort

    service:
      main:
        ports:
          http:
            port: *port
      metrics:
        ports:
          metrics:
            port: *metricsPort

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:movie-search"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host prowlarr.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    persistence:
      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/prowlarr
        mountPath: /config/Backups
        readOnly: false

    volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 65539

    resources:
      requests:
        memory: 350Mi
        cpu: 5m
      limits:
        memory: 431Mi

    serviceMonitor:
      metrics:
        enabled: true
        serviceName: prowlarr-metrics
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 5m
          scrapeTimeout: 2m
