---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            vpn.home.arpa/enabled: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 1.35.1.5034@sha256:f9c4e4c7dedcbc9ec9c9616cbaacc5ca908a063b86d4f052db0e83f27c48bf3f
            env:
              COMPlus_EnableDiagnostics: "0"
              TZ: America/New_York
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__APPLICATION_URL: "https://prowlarr.${EXTERNAL_DNS_1_DOMAIN}"
              PROWLARR__ANALYTICS_ENABLED: "False"
              PROWLARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: prowlarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 350Mi
                cpu: 5m
              limits:
                memory: 431Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          exporter:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.2.0
            args:
              - prowlarr
              - --enable-additional-metrics
            env:
              URL: "http://localhost:9696"
              PORT: &metricsPort 9710
            envFrom:
              - secretRef:
                  name: prowlarr-secret
            ports:
              - name: metrics
                containerPort: *metricsPort

    service:
      prowlarr:
        controller: prowlarr
        ports:
          http:
            port: *port
          metrics:
            port: *metricsPort

    ingress:
      prowlarr:
        className: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:movie-search"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host prowlarr.${EXTERNAL_DNS_1_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: prowlarr
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
        advancedMounts:
          prowlarr:
            app:
              - path: /config
                readOnly: false

    serviceMonitor:
      metrics:
        serviceName: prowlarr-metrics
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 5m
            scrapeTimeout: 2m
