---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
  labels:
    substitution.flux.home.arpa/enabled: "false"
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.15

    initContainers:
      user-import:
        image: public.ecr.aws/docker/library/eclipse-mosquitto:2.0.16@sha256:0dd856ccc3da592b27a55a01f06498b70cf15dcf80f9ac66eaed0f4c9fe558d1
        command:
        - "/bin/sh"
        - -c
        args:
        - /data/mosquitto_init/load-users.sh /data/mosquitto_secret /data/external_config/mosquitto_pwd && mosquitto_passwd -U /data/external_config/mosquitto_pwd && echo "User import Completed"
        volumeMounts:
        - name: mosquitto-secret
          mountPath: /data/mosquitto_secret
        - name: mosquitto-init-config
          mountPath: /data/mosquitto_init
        - name: external-config
          mountPath: /data/external_config

    sidecars:
      exporter:
        name: exporter
        image: sapcc/mosquitto-exporter:0.8.0
        env:
        - name: BROKER_ENDPOINT
          value: "tcp://127.0.0.1:1883"
        - name: MQTT_USER
          valueFrom:
            secretKeyRef:
              name: mosquitto-secret
              key: MOSQUITTO_USER
        - name: MQTT_PASS
          valueFrom:
            secretKeyRef:
              name: mosquitto-secret
              key: MOSQUITTO_PASS
        ports:
        - name: metrics
          containerPort: &metricsPort 9234

    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_MQTT}
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
      metrics:
        ports:
          metrics:
            port: *metricsPort

    persistence:
      mosquitto-config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      mosquitto-secret:
        enabled: true
        type: secret
        name: mosquitto-secret
        mountPath: "-"
      mosquitto-init-config:
        enabled: true
        type: configMap
        name: mosquitto-init-config
        mountPath: "-"
        defaultMode: 0755
      external-config:
        enabled: true
        type: emptyDir
        mountPath: /mosquitto/external_config

    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 10Mi

    volumeClaimTemplates:
    - name: data
      mountPath: /data
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    serviceMonitor:
      metrics:
        enabled: true
        serviceName: mosquitto-metrics
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 30s
          scrapeTimeout: 10s
