---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  labels:
    substitution.flux.home.arpa/enabled: "false"
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      mosquitto:
        type: statefulset

        pod:
          annotations:
            reloader.stakater.com/auto: "true"

        initContainers:
          user-import:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.21
            command:
              - /bin/sh
              - -c
            args:
              - /data/mosquitto_init/load-users.sh /data/mosquitto_secret /data/external_config/mosquitto_pwd && mosquitto_passwd -U /data/external_config/mosquitto_pwd && echo "User import Completed"

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.21
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 512Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &mqttPort 1883
              readiness:
                enabled: false

          exporter:
            image:
              repository: sapcc/mosquitto-exporter
              tag: 0.8.0
            env:
              BROKER_ENDPOINT: tcp://127.0.0.1:1883
            envFrom:
              - secretRef:
                  name: mosquitto-secret
            ports:
              - name: metrics
                containerPort: &metricsPort 9234
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: *metricsPort
              readiness: *probes

    service:
      main:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_MQTT}
        ports:
          http:
            port: *metricsPort
          mqtt:
            port: *mqttPort

    persistence:
      data:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/data
                readOnly: false

      mosquitto-config:
        type: configMap
        name: mosquitto-config
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf

      mosquitto-secret:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          mosquitto:
            user-import:
              - path: /data/mosquitto_secret

      mosquitto-init-config:
        type: configMap
        name: mosquitto-init-config
        defaultMode: 0755
        advancedMounts:
          mosquitto:
            user-import:
              - path: /data/mosquitto_init

      external-config:
        type: emptyDir
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/external_config
            user-import:
              - path: /data/external_config

    serviceMonitor:
      metrics:
        serviceName: mosquitto
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 30s
            scrapeTimeout: 10s
