---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./secret-mosquitto.sops.yaml
- ./helmrelease.yaml
- ../../../../templates/volsync
commonLabels:
  app.kubernetes.io/name: mosquitto
  app.kubernetes.io/instance: mosquitto
configMapGenerator:
- name: mosquitto-config
  files:
  - files/mosquitto.conf
- name: mosquitto-init-config
  files:
  - files/load-users.sh
- name: mosquitto-grafana-dashboards
  files:
  - ./dashboards/mosquitto.json
  options:
    annotations:
      grafana.io/folder: Home
    labels:
      grafana.io/dashboard: "true"
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
