apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: nvr
stringData:
    MOSQUITTO_USER: ENC[AES256_GCM,data:69p1Kw==,iv:5Bgwo8RZDhYYq8LxzMbmwH7mRnnCWmPvfVAfQVlsegY=,tag:/VGIoey7RNrrLnUwhx6FIw==,type:str]
    MOSQUITTO_PASS: ENC[AES256_GCM,data:dW3EV0duVdOR7yfL8vivNpjBTzI05bfL,iv:1ShpS6xiNyzHNFUo9wr2l13amnMyTUbB1YVSi7XDxzk=,tag:99DZ6NyimZHXdWet7BqhzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQktKNTBLTnNpVXpITUtB
            V3dIYzNjTUg1akcvM202cWRyMDhlTDd5RWtvCmVWeC83VUxhSXZRaTBwc1hNOFJs
            bndOOEd5c0R0RGFaL3pCMERpTTFnR3MKLS0tIDdpbzZlN0tyZ084VnZZRkFUYnNQ
            VUdyTkE4VUEramZFOFZqOUlqcThYczQK5QsGy8cxzP3AFTDuqxX02G+qOKDq0DQ4
            dmof2R8zrPZFhKYI88gYoraE6SPoEbziSR3xFCUOX87wFYqMZz9Prg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-30T04:34:38Z"
    mac: ENC[AES256_GCM,data:BlDuESCVsk43IQVe48yVMyMBew2T7MGvy2lNu/1CkQAHkkprPgs8wZ8TIty1/rY7gryC/EbzanMw7aw2cZrGCyK/Jn13mHK7q0olJkzI6uZODzW62l+6uBH1gZyTH1XOg4N9UAb2PqVtcafLhzsu9xfA3XlKZG+hLFtNbjs2r8M=,iv:yo0iUlsKX35qW+hvm0zpbKA56GFvUBnL37cKa5+lCcE=,tag:G24ZfoqKiQaYu9Z2oyjwEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
