---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/ingress/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: monitoring-kube-prometheus-stack-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/ingress/cert-manager/issuers"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: ingress-cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-cert-manager-certs
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/ingress/cert-manager/certs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: ingress-cert-manager-issuers
