---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-ha-fpp-mqtt
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/home/ha-fpp-mqtt/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: home-mosquitto
  - name: home-home-assistant
