apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secrets
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: flux-system
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:U9a7zRr8F8Tquz15LoLqzpM5cWrCdmQF,iv:DGG6AKjvP+llI4LgzHnshA8UR04aesAMEjYFFN1c4FQ=,tag:pthlRTMousT6DLfi+091Vg==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:nwzcMH0qFX/G/Q==,iv:12cH8QhYPBGviFgNaUZDaH9USZFO2SsYvzw/hfLHeUQ=,tag:ApOPfMRyWRm87DNMKR6fGw==,type:str]
    MARIADB_USERNAME: ENC[AES256_GCM,data:sQ8Eo6a+9UXeuw==,iv:71KhIS1/2GpiDvB6vh6sgk1zySiC/Gx0j6gYKjs5LCk=,tag:hv4Y/fDRaGRVCxeaCKRXSA==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:lzh2zOg+52qId/AOpbfAulFWjRNGpvlf,iv:5ONUGIEdHMusefs3QzYd6XHiLo4Jnxw9CSwaShloa1s=,tag:cCFh0GXUuihxrcrOZAVXNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUm1nZ01iRXIyM3ptSDE1
            OGxhTXNaOFJ3aFlsblNBT2JZb0JaUnFTeEhvCjhOUVZBcGM5RldzVnBHdlBoNTVt
            N1l2Wk04dUt4RDhJc0EyUUdhREJ5Qk0KLS0tIDY5eDA1OUl5VDgvUXFVdnpIeHFq
            dUwwa2pyTm1TUFR0SWNUbzhsVVBhdDgKCv2UjQzSdW1PjeGYO9NCqBdxZ+f3bk06
            h9fNG3KhAgCBV5Cn9YRhu758CkHfwqgHUD63+yESxSQMGRX80C5MHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T20:43:39Z"
    mac: ENC[AES256_GCM,data:m0yQsPGPFW9CLzmIslen+W8QvGI8JuxiRgfErVBETSYPXIhCe5MR9SKY6Pvm1fWMOMbB0c///BFbq+wAQbUYrB3bdCmZTeHGHtqhQT4sOurzyfexNF+Dj2k8hdFGb3xPA3ZxVKrcHywK/2sKRxhFduhVHcmS8ucGyhSshjTl+XI=,iv:dvVL2a3PAikk8UlAtv4n5Y+sN35aVqwpW+fbjtqxApE=,tag:+HePNDqPvd6tU7qm7B3dyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
