---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.1.0@sha256:1c1650511f96108e81d677abe8a2e491507caa023fdc5c2bfc99df087634c9f3

    podAnnotations:
      vpn.home.arpa/enabled: "true"

    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.downloads,
        sabnzbd.downloads.svc,
        sabnzbd.downloads.svc.cluster,
        sabnzbd.downloads.svc.cluster.local,
        sabnzbd.${EXTERNAL_DNS_1_DOMAIN}
      SABNZBD__API_KEY:
        valueFrom:
          secretKeyRef:
            name: starr-apps-secret
            key: SABNZBD_API_KEY
      SABNZBD__NZB_KEY:
        valueFrom:
          secretKeyRef:
            name: starr-apps-secret
            key: SABNZBD_NZB_KEY

    sidecars:
      exporter:
        name: exporter
        image: ghcr.io/onedr0p/exportarr:v1.6.0
        args:
        - sabnzbd
        env:
        - name: URL
          value: "http://localhost:8080"
        - name: PORT
          value: &metricsPort 9710
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: starr-apps-secret
              key: SABNZBD_API_KEY
        ports:
        - name: metrics
          containerPort: *metricsPort

    service:
      main:
        ports:
          http:
            port: *port
      metrics:
        ports:
          metrics:
            port: *metricsPort

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:download-circle-outline"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host sabnzbd.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    persistence:
      media:
        enabled: true
        existingClaim: nfs-downloads
        mountPath: /data/downloads

      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/sabnzbd
        mountPath: /backups
        readOnly: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 65539

    resources:
      requests:
        cpu: 5m
        memory: "2392M"
      limits:
        memory: "2392M"

    serviceMonitor:
      metrics:
        enabled: true
        serviceName: sabnzbd-metrics
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 5m
          scrapeTimeout: 2m
