---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      *app :

        pod:
          annotations:
            vpn.home.arpa/enabled: "true"
            reloader.stakater.com/auto: "true"

          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
            - 65539
            - 1030

        containers:
          *app :
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.3.2
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.${EXTERNAL_DNS_1_DOMAIN}
              SABNZBD__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: SABNZBD_API_KEY
              SABNZBD__NZB_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: SABNZBD_NZB_KEY
            resources:
              requests:
                cpu: 5m
                memory: 2392M

    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
            primary: true

    ingress:
      *app :
        className: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:download-circle-outline"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host sabnzbd.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: *app
              port: *port

    persistence:
      media:
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/media/downloads
        advancedMounts:
          *app :
            *app :
            - path: /data/downloads
              readOnly: false

      config:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
        - path: /config

      backups:
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/sabnzbd
        advancedMounts:
          *app :
            *app :
            - path: /backups
              readOnly: false
