---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-ingress-nginx
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/ingress/ingress-nginx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: ingress-cert-manager-certs
  - name: ingress-external-dns-1
  - name: ingress-external-dns-2
