---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deepstack
  namespace: nvr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: docker.io/deepquestai/deepstack
      tag: cpu@sha256:4320be73987468b3040b2ca63daf2d3935c4d469b53aa40efb6176858488b500
      pullPolicy: IfNotPresent

    env:
      VISION-FACE: "True"
      VISION-DETECTION: "True"

    envFrom:
    - secretRef:
        name: deepstack-secret

    additionalContainers:
      ui:
        image: docker.io/robmarkcole/deepstack-ui:latest@sha256:41027572645947141c217e530e102297d4be4a0cfbfb870d3f3fcecd09c72e85
        imagePullPolicy: IfNotPresent
        env:
        - name: DEEPSTACK_IP
          value: localhost
        - name: DEEPSTACK_PORT
          value: '5000'
        - name: DEEPSTACK_API_KEY
          value : '{{ index .Values.env "API-KEY" }}'
        ports:
        - name: ui
          containerPort: 8501
          protocol: TCP

    service:
      main:
        enabled: true
        ports:
          ui:
            enabled: true
            port: 8501
          http:
            port: 5000

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: cctv
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: deepstack.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              port: 8501

    volumeClaimTemplates:
    - name: datastore
      mountPath: /datastore
      accessMode: ReadWriteOnce
      size: 1Gi
      stoageClass: ceph-block

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - frigate
          topologyKey: "kubernetes.io/hostname"
