---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvr
resources:
- ./secret-deepstack.sops.yaml
- ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: deepstack
  app.kubernetes.io/instance: deepstack
