apiVersion: v1
kind: Secret
metadata:
    name: deepstack-secret
    namespace: nvr
stringData:
    values.yaml: ENC[AES256_GCM,data:SYMtA71RH+vmauTDtjgatl9ADJwwW3hdUnvI91EjnR5mXqmecwmrF8vAZhKxO18XcyhOypPUU3A2+MjhMYzWnwdj7D6r9Q==,iv:kbGjcdTOgJrfRBgX6m0k0CTypMJCZP6dZIhONTlXefc=,tag:u/7sYvr+xbTFyQmZgDBQkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxelZJU3h3U0dGTVhFQzdK
            Q25PWE56NlFXSy9teDFFRllZMVI1SklRUVRjCjZ6a3VmS0tVTEJVTDc3MkMvd2pn
            NEpuUWN3ZWJLVE5LU1E2NjhLa2RrTzQKLS0tIGtpQ0hOVzZ2Y3dOZlNGSEhvUVFp
            S09Ja3Vaejh5aVJnWGlhUnBUMVdFNHcKYD7BmAWqldL0QUgxz/KRaSwcyOYUAWoB
            q4YrvZvKpSCgclErgBUO9P1L5xgZV16m3dC6Nv7moyDXqx4SHR8lDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-30T06:01:59Z"
    mac: ENC[AES256_GCM,data:4q0YVS4QbFwQWdwKxJ6Gd8hRDSkEDfVgmdIOKUptAtyZWkaYhIloTYVhs4/8KJp830DwetI9fUKOutTEuinnOurIzHB6MmTaccnqkev2aTc34zxnNd0VjxylslkSEl2CT8qrJlSlhKDEMtbfbgFILwmg3XCg0q2ULaDvX/ymzCc=,iv:UmsHnFwhgfnvV+yHoqxq5PBoXKuM+4+68C0DLbYqsYY=,tag:RumwYdtTZz0knX6M05Smjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
