---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65539
              - 1030

        containers:
          *app :
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.22.0.9808@sha256:2bf6a9a5f30b28f09fa5601b23d095c64739ab0667753b95493a1bcdf194057d
            env:
              TZ: America/New_York
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
              RADARR__APPLICATION_URL: https://radarr.${EXTERNAL_DNS_1_DOMAIN}
              RADARR__LOG_LEVEL: info
              RADARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: RADARR_API_KEY
            resources:
              requests:
                memory: 350Mi
                cpu: 5m
              limits:
                memory: 431Mi

          exporter:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.1.0
            args:
              - radarr
            env:
              - name: URL
                value: "http://localhost:7878"
              - name: CONFIG
                value: "/config/config.xml"
              - name: PORT
                value: &metricsPort 9710
              - name: ENABLE_ADDITIONAL_METRICS
                value: true
              - name: APIKEY
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: RADARR_API_KEY
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
            primary: true
          metrics:
            port: *metricsPort

    ingress:
      *app :
        className: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:movie-open-outline"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host radarr.${EXTERNAL_DNS_1_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: *port

    persistence:
      media:
        existingClaim: nfs-media
        advancedMounts:
          *app :
            *app :
              - path: /media

      config:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /config

      backups:
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/radarr
        advancedMounts:
          *app :
            *app :
              - path: /config/backup
                readOnly: false

    serviceMonitor:
      metrics:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 10m
            scrapeTimeout: 10s
