---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: compreface
  namespace: nvr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset

    image:
      repository: exadel/compreface
      tag: 1.2.0-arcface-r100@sha256:5aeebdee56b91b57e348e55df7481f59799ff4193a3fe0585e7e6dd2a7dd6c01

    env:
      TZ: "America/New_York"
      EXTERNAL_DB: true
      SAVE_IMAGES_TO_DB: true
      POSTGRES_URL: "jdbc:postgresql://postgres-compreface-rw.nvr.svc.cluster.local:5432/compreface"
      POSTGRES_USER:
        valueFrom:
          secretKeyRef:
            name: &dbSecret "postgres-compreface-app"
            key: username
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: *dbSecret
            key: password

    service:
      main:
        ports:
          http:
            port: 8000
            targetPort: 80

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host compreface.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    resources:
      requests:
        cpu: 10m
        memory: 1Gi
      limits:
        memory: 6Gi

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - frigate
          topologyKey: "kubernetes.io/hostname"
