---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvr
resources:
- ./pgcluster.yaml
- ./helmrelease.yaml
labels:
- pairs:
    app.kubernetes.io/name: compreface
    app.kubernetes.io/instance: compreface
    app.kubernetes.io/part-of: compreface
