---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-rook-ceph
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/storage/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: monitoring-kube-prometheus-stack-crds
  - name: storage-snapshot-controller
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/storage/rook-ceph/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: storage-rook-ceph
