---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-data
  namespace: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
