---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyze-bridge
  namespace: nvr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      wyze-bridge:
        type: deployment

        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/mrlt8/docker-wyze-bridge
              tag: nightly-hw@sha256:d46767fae46f23fa304685d72e937550d611318e1d6d97b3bb536d283cc8035f
            env:
              ENABLE_AUDIO: "true"
              NET_MODE: "LAN"
              FRESH_DATA: "true"
              H264_ENC: "h264_qsv"
              FILTER_MACS: "2CAA8E16BC21,2CAA8E146DE5"
              FILTER_BLOCK: "true"
              WB_AUTH: "false"
              AUDIO_CODEC: "AAC"
              # FFMPEG_CMD: "ffmpeg -loglevel verbose -hwaccel qsv -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 100 -hwaccel qsv -analyzeduration 50 -probesize 50 -f H264 -i pipe: -thread_queue_size 100 -f alaw -ar 16000 -i /tmp/{cam_name}.wav -flags +global_header -c:v h264_qsv -c:a copy -movflags +empty_moov+default_base_moof+frag_keyframe -muxdelay 0 -muxpreload 0 -map 0:v -map 1:a -async 100 -f tee [f=rtsp:rtsp_transport=tcp:bsfs/v=dump_extra=freq=keyframe]rtsp://0.0.0.0:8554/{cam_name}"
            envFrom:
            - secretRef:
                name: wyze-bridge-secret
            resources:
              requests:
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 16Gi

        service:
          wyze-bridge:
            controller: wyze-bridge
            type: LoadBalancer
            annotations:
              io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_WYZE_BRIDGE}
            ports:
              rtmp:
                enabled: true
                port: 1935
              rtsp:
                enabled: true
                port: 8554
              hls:
                enabled: true
                port: 8888
              http:
                enabled: true
                port: 5000

        ingress:
          wyze-bridge:
            annotations:
              nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              hajimari.io/enable: "true"
              hajimari.io/icon: "mdi:camera-wireless"
            className: nginx
            hosts:
            - host: "wyze.${EXTERNAL_DNS_1_DOMAIN}"
              paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: wyze-bridge
                  port: http
