---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyze-bridge
  namespace: nvr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: deployment
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/mrlt8/docker-wyze-bridge
      tag: dev-qsv@sha256:4db2cb8cc6504dc8084ed7deeb58fc8b36bfab96423c98e967136902ab383bf7

    envFrom:
    - secretRef:
        name: wyze-bridge-secret

    env:
      ENABLE_AUDIO: "true"
      NET_MODE: "LAN"
      FRESH_DATA: "true"
      H264_ENC: "h264_qsv"
      FILTER_MACS: "2CAA8E16BC21,2CAA8E146DE5"
      FILTER_BLOCK: "true"
      WB_AUTH: "false"
      # FFMPEG_CMD: "ffmpeg -loglevel verbose -hwaccel qsv -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 100 -hwaccel qsv -analyzeduration 50 -probesize 50 -f H264 -i pipe: -thread_queue_size 100 -f alaw -ar 16000 -i /tmp/{cam_name}.wav -flags +global_header -c:v h264_qsv -c:a copy -movflags +empty_moov+default_base_moof+frag_keyframe -muxdelay 0 -muxpreload 0 -map 0:v -map 1:a -async 100 -f tee [f=rtsp:rtsp_transport=tcp:bsfs/v=dump_extra=freq=keyframe]rtsp://0.0.0.0:8554/{cam_name}"

    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_WYZE_BRIDGE}
        ports:
          rtmp:
            port: 1935
          rtsp:
            port: 8554
          hls:
            port: 8888
          http:
            port: 5000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:camera-wireless"
        hosts:
        - host: "wyze.${EXTERNAL_DNS_1_DOMAIN}"
          paths:
          - path: /
            service:
              port: 5000

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - frigate
          topologyKey: "kubernetes.io/hostname"
