apiVersion: v1
kind: Secret
metadata:
    name: wyze-bridge-secret
    namespace: nvr
stringData:
    WYZE_EMAIL: ENC[AES256_GCM,data:4HNGVij7TLcDQ4yBn+qJhTy3vNT/bBjlCw==,iv:sQNSH9rTzAwLdrIa+uJkHyhL0fSgGlmp6vR7LqDT+qQ=,tag:DVdQdLTnpPIsOkLcqoyaLg==,type:str]
    WYZE_PASSWORD: ENC[AES256_GCM,data:bQX8lk0W6CCUrFp8voEyHwrbgiY=,iv:x3/FmwrDhJt+bn1r73mjyyzGRNTC6dhulQ35TtnKEEU=,tag:85wK/E76lKCJvxvoWvOcoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSFN4MXNpRU9qN0FUcHpO
            TlRmcG93WmllYldIY0gxd3NIRnFIaU82blNrCjd5SHMyVE9Ud0tJY09WSVRCQWNQ
            Syt3VXdmeG5aRXFTMXVEV0g5WTAyQ0kKLS0tIEtaYWxJTnNBaG5GbzF3U295TlZv
            R2ptMVZJTVg5NkE1VEZmbTRQSnJnSE0KyW5nVCAQZQJIrqKFuPSTejj1uoOztjeA
            8cl4vpUMRi31XoQuZpew0BR4IxXQEU8raiDgkxY2XwqabWYIcj/hDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T09:39:16Z"
    mac: ENC[AES256_GCM,data:AgDrqJrkS1uIknTT4OcogNDBbirX80OUElhq6y4T9n7tq4yj+xJ7AqF30fQXc3BB2TwVHz0EfgBr0cviqV7mEIzYVAJg8QMcRcaBKjeC1otW9OIgZwG+tVbd5aEZrrK5iYKlj1kJAb1sC5az5fzYnHU9mrJ5q84/Udlqs90nbJc=,iv:e4ZOA8TVHjf6dTKz+i6A1J5/uKLA1zPYgzWzzodL2gs=,tag:TTOImJHypyPuNXJnY5loeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
