---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-drone
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/development/drone/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: storage-rook-ceph-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development-drone-runner-docker
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/development/drone/runner-docker"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: development-drone
