---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./secret-photoprism.sops.yaml
commonLabels:
  app.kubernetes.io/name: photoprism-cvd
  app.kubernetes.io/instance: photoprism-cvd
  app.kubernetes.io/part-of: photoprism
