apiVersion: v1
kind: Secret
metadata:
    name: photoprism-cvd-secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: flux-system
stringData:
    MARIADB_CVD_ROOT_PASSWORD: ENC[AES256_GCM,data:I2U/BVBOGig829dyunl/afIzG52RwEUv,iv:zozbCXSei4BG2VOyQOxjoc7EztD8NQ700XVYZ7MjxZY=,tag:WJNkhsWVcY8SfEF+XgpoMg==,type:str]
    MARIADB_CVD_DATABASE: ENC[AES256_GCM,data:bIT0CAyAB3JaOA==,iv:PImqUEkFigvikpq5U7gI8PU6z0CfIfxoR3zocZgdMoI=,tag:rWQ+nXXzkgtLOL4fmwv7qg==,type:str]
    MARIADB_CVD_USERNAME: ENC[AES256_GCM,data:cVNodVbhmLCTnw==,iv:TFSWqCBgiSIn4aOAuoYzdkEk2Zsor6Lm6GJLH2i2EdE=,tag:OpKs9V4EUkSbn0VN6MiA5A==,type:str]
    MARIADB_CVD_PASSWORD: ENC[AES256_GCM,data:5pqmkQ7q3dH7a7p6zlKLQrAA8Xdv0ZQ8,iv:IYnL6BLj87UYQ5qq25RvVuxsJScll6bhLBEiY5auX0Q=,tag:N89XHFv3crKnI+jVDnIGgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUm1nZ01iRXIyM3ptSDE1
            OGxhTXNaOFJ3aFlsblNBT2JZb0JaUnFTeEhvCjhOUVZBcGM5RldzVnBHdlBoNTVt
            N1l2Wk04dUt4RDhJc0EyUUdhREJ5Qk0KLS0tIDY5eDA1OUl5VDgvUXFVdnpIeHFq
            dUwwa2pyTm1TUFR0SWNUbzhsVVBhdDgKCv2UjQzSdW1PjeGYO9NCqBdxZ+f3bk06
            h9fNG3KhAgCBV5Cn9YRhu758CkHfwqgHUD63+yESxSQMGRX80C5MHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T06:56:31Z"
    mac: ENC[AES256_GCM,data:W0f+k90K+iFp2lQiZmiTjiGtugCIP/2UMDOzoPe3iwd8Du14xdWvPJrug+TQP0bOCdZFAq0CuiT9rHWVzqCjGK8dDPNJL/Yh08BWym58k10MMzy6+maf4QWJ9Bdbnl7c4BZ/zIlZRJMU0r2+7fRyDXGqoi9dMiKsFhO4ubnu9s8=,iv:pWdWtcQOWgKnCUV1GxeSZzO3FloaUcCzGWh4yJUdM0k=,tag:EFTgHt3ieH9ONlGKFk/p3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
