---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: porla
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    automountServiceAccountToken: false

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/porla/porla
      tag: beta-latest@sha256:40d9a8a94792ca06522486327db32632a80630513862101810657930ea05a65e

    podAnnotations:
      vpn.home.arpa/enabled: "true"

    env:
      PORLA_STATE_DIR: /config
      PORLA_CONFIG_FILE: /config/config.toml
      PORLA_LOG_LEVEL: debug

    service:
      main:
        ports:
          http:
            port: &httpPort 1337

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:download-circle-outline"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host porla.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]

    volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    persistence:
      porla-config:
        enabled: true
        type: configMap
        name: porla-config
        mountPath: /config/config.toml
        subPath: config.toml
        readOnly: true
      media:
        enabled: true
        existingClaim: nfs-downloads
        mountPath: /media

    extraVolumeMounts:
    - name: porla-workflows
      mountPath: /workflows
      readOnly: true

    extraVolumes:
    - name: porla-workflows
      configMap:
        name: porla-workflows

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2Gi
