---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-zigbee2mqtt
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/home/zigbee2mqtt/app
  targetNamespace: home
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: zigbee2mqtt
      VOLSYNC_CLAIM: zigbee2mqtt-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom: []
  dependsOn:
  - name: home-mosquitto
  - name: storage-rook-ceph
  - name: system-node-feature-discovery-rules
