---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal-database
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: 15.5.22
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    image:
      repository: bitnami/postgresql
      tag: 16.4.0-debian-12-r1

    auth:
      database: temporal
      existingSecret: temporal-database-secrets

    primary:

      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_TEMPORAL_POSTGRES}

      persistence:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}

      resources:
        requests:
          cpu: 2
          memory: 512Mi
        limits:
          memory: 2048Mi
