apiVersion: v1
kind: Service
metadata:
  name: pg-temporal-home
  annotations:
    io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_TEMPORAL_POSTGRES}
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: pg-temporal
  ports:
  - name: postgres
    protocol: TCP
    port: &dbPort 5432
    targetPort: *dbPort
