---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cilium
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/networking/cilium/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: monitoring-kube-prometheus-stack-crds
  - name: ingress-cert-manager-issuers
