apiVersion: v1
kind: Secret
metadata:
  name: ffxi-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: flux-system
stringData:
  MARIADB_FFXI_ROOT_PASSWORD: ENC[AES256_GCM,data:iLxyIKv9stuRBRQVbmKqoGCz1HzEh0mD,iv:+xnbHEIYI1PWYc1lWm+8UmJCG8Hl/ZqHzTxebvlTBP0=,tag:AyOysWU5Y1E9rJMlJuBP0w==,type:str]
  MARIADB_FFXI_DATABASE: ENC[AES256_GCM,data:Sdtoy2XJ,iv:FNBYggxsMOhZLDk01MmL/tPRYrMuiTwzN7rnX/co118=,tag:fjCHAU+0HoHDc2yeHqsw6Q==,type:str]
  MARIADB_FFXI_USERNAME: ENC[AES256_GCM,data:JVSFYhwfUvC00oN9LUv8gcsAOt0pfqt1,iv:SMQxMi4wBApi98qn528AaH2pkZmse5dF+37LUNQ6rg8=,tag:SfVlM95dX7wrHZx4EHuT4Q==,type:str]
  MARIADB_FFXI_PASSWORD: ENC[AES256_GCM,data:TOUmhuCSKtY0Q1uPnYcdxx60BwLXTqPa,iv:7GVFLEmC/Ua7E3nAZxGSYKuf+exvagtjCXtPS//pHGM=,tag:Sax9fKsMAbJ0N+rMhh3DMA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmJYa0EzeFlGRktWYjBT
        eVhWeUpMRzBXU2IxSVV4NCtqNnh3MXZKT0hrCkhIYVhoMFh5di90TWVMMW9McGpn
        eVh6b3ZvUUdBcXkwLy9WWmR2clgxQ00KLS0tIDlDZysyY1ByZjlBMW52L282Q1RT
        eXY3RENKN0hyNFNoVVBRdlNzUGRhUTgKdVyg1/zqOCHYy3m0sMZLu1jHb/Nwlrjd
        wNG0s8l0KL2TWXOkqrDCNZBWDXhajCxNDkLOFz+g/N31N/P3Gz+V5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-07T02:41:18Z"
  mac: ENC[AES256_GCM,data:YgZfSy3ySda0SeZn6iFuIEttPCFrldRjuONzSTo4yqfjRY+nvd7v0fLlQc7ULgWcfGpy+cwIUl3FCnEkeJx2Ml1q9uHHdtLJ6ASKmBJiU4ouu7Jc+bdD5Ay2VUYtGA62dfrCyfujQsjCqkp4ge6yZedGlkjS5tuJ2UBFGxMZnyg=,iv:9kB1peXz8i8tljK393jCURZ271QexTBTPPmJtLAjcuU=,tag:SuEvHzg/Uvul+NoSeqlC8g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
