---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: deluge
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: tccr.io/truecharts/deluge
      tag: 17.1.6@sha256:2e8bc07b3a74a98535213c46751af67f71f733d1838e0e775279974afadcf4ee

    podAnnotations:
      vpn.home.arpa/enabled: "true"

    service:
      main:
        ports:
          http:
            port: &httpPort 8112
          daemon:
            port: &daemonPort 57120

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:download-circle-outline"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: &host deluge.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    persistence:
      media:
        enabled: true
        existingClaim: nfs-downloads
        mountPath: /data/downloads
