---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: k8s-home-ops
  CLUSTER_APISERVER_ENDPOINT: 192.168.10.30
  SYNOLOGY_ADDRESS: 192.168.10.20
  INGRESS_INTERNAL_ONLY_CIDR: 192.168.0.0/16

  SERVICE_ADDRESS_NGINX: 10.13.37.1
  SERVICE_ADDRESS_WYZE_BRIDGE: 10.13.37.2
  SERVICE_ADDRESS_MQTT: 10.13.37.3
  SERVICE_ADDRESS_PLEX: 10.13.37.4
  SERVICE_ADDRESS_VPN: 10.13.37.5
