---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: k8s-home-ops
  CLUSTER_APISERVER_ENDPOINT: 192.168.10.30
  SYNOLOGY_ADDRESS: 192.168.10.20
  DABEAST_ADDRESS: 192.168.8.197
  FRIGATE_ADDRESS: 192.168.10.82
  INGRESS_INTERNAL_ONLY_CIDR: 192.168.0.0/16

  SERVICE_ADDRESS_NGINX: 192.168.12.10
  SERVICE_ADDRESS_WYZE_BRIDGE: 192.168.12.11
  SERVICE_ADDRESS_MQTT: 192.168.12.12
  SERVICE_ADDRESS_PLEX: 192.168.12.13
  SERVICE_ADDRESS_VPN: 192.168.12.14
  SERVICE_ADDRESS_HOME_ASSISTANT: 192.168.12.15
  SERVICE_ADDRESS_ZWAVEJSTOMQTT: 192.168.12.16
  SERVICE_ADDRESS_WYOMING_PIPER: 192.168.12.17
  SERVICE_ADDRESS_FRIGATE: 192.168.12.18
  SERVICE_ADDRESS_VECTOR_AGGREGATOR: 192.168.12.19
  SERVICE_ADDRESS_TEMPORAL_SERVER: 192.168.12.20
  SERVICE_ADDRESS_TEMPORAL_POSTGRES: 192.168.12.21
  SERVICE_ADDRESS_TEMPORAL_UI: 192.168.12.22
  SERVICE_ADDRESS_FFXI_DB: 192.168.12.23
