apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:HQ5rc7K4D1iYyXyHqq/4HBsaFyk=,iv:LW1j81klsELXDOWYpDDgRNJYGgOA2v7c+dlc3Uvpt20=,tag:so+8hek42SSMIRurDoymdQ==,type:str]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:VSpsEkyUGSucGWDjRODIa7oH5R0=,iv:8xHJqWndGKHFCDqKy6ytZKV9WBm7X0iacRD99xkhJs8=,tag:f70ihQzWKne7sbByPCvobQ==,type:str]
    CERT_MANAGER_DOMAIN_1: ENC[AES256_GCM,data:SFpyFwlLtt95+Xp4J58=,iv:mnPd2D6MesWQSDpf5gDoyBqG8FbiMr9Uewzid/95o4M=,tag:ZxVpIDxPRz5Fv1RBDFXwPw==,type:str]
    CERT_MANAGER_DOMAIN_2: ENC[AES256_GCM,data:8UlKl2Lywdiz9cqr,iv:57hEzREpbqaFz2GLdlJWtGdoSx3+08k3HwR3bpsb+a8=,tag:WbtSWV4JumKdqH65QXLFRw==,type:str]
    CERT_MANAGER_DOMAIN_3: ENC[AES256_GCM,data:6XQzb9wF5XdhMhXja7H+,iv:IbIRTTD8lGGaqoabPtwN1WbmBICSicgrFhtzCYnmffo=,tag:TECxQjctmydHbzN/ZKRwlg==,type:str]
    CERT_MANAGER_DOMAIN_4: ENC[AES256_GCM,data:STVzecfs,iv:MSe0vb6G/vKKidStSy7qRWX1XnDtY/QQMtUJHW3GIL4=,tag:ZrMPuonqQUDKCW640FbhBA==,type:str]
    CERT_MANAGER_DOMAIN_5: ENC[AES256_GCM,data:/pp5F4SEmNt8YK8=,iv:JqgQYhAIYWKFNiD0IXWbPoI4pNjCVVZks9s7jzYXAp0=,tag:lSsSDpcKoxEsKM82pdtWPw==,type:str]
    CERT_MANAGER_DOMAIN_6: ENC[AES256_GCM,data:ayNUREukKttzdXBO,iv:qLeoKrl7M83Ll72UvgPvEDr8xkX8ees4XteWU3rDkAg=,tag:N28TnPmiBQMQZHbgzkncpw==,type:str]
    CERT_MANAGER_AWS_REGION: ENC[AES256_GCM,data:07lIvBQiL5qf,iv:mqnv4W20L4uKsvSQogKjQ9OwSaILvzY6MXLprXS+NBc=,tag:e0cGvIgflFlihHnkS6NUdA==,type:str]
    EXTERNAL_DNS_1_DOMAIN: ENC[AES256_GCM,data:Uo3Gc47F,iv:vdSya/JCgMW6Z57rnaXnH0o8/5hOrXQ5yOR/eV55YQg=,tag:m0Hu1U1lx3wmrbDFWS5aTA==,type:str]
    EXTERNAL_DNS_2_DOMAIN: ENC[AES256_GCM,data:R8Yp5LzVU6ZSCmU=,iv:knqAL6G3fUJiCmka9HVuzjJPeCMamCgWdk6arfVq7XM=,tag:gPXBn76swoddBCiW7jHElQ==,type:str]
    MINIO_S3_URL: ENC[AES256_GCM,data:Mn6hO2Vg44iUy9MlhD1O7U8J,iv:Xc8Cth1zI3ODR/zeaa2NmMvYSoHBH4GuINsviwk5apY=,tag:vLSdWpFAH61XnRqsWh4Yqw==,type:str]
    VOLSYNC_S3_BUCKET_NAME: ENC[AES256_GCM,data:F+45Wdr/CVUgqrbh+6LA,iv:Y1JbRsgqbdo8dg3Loa0IruKt7n+wz0wOi/dVQSYy19w=,tag:nafEW4hk3L8n4DHkCis/hw==,type:str]
    VOLSYNC_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:Avl2E9MbV7NqCV5yQE2GOwPFMjU=,iv:fbppFrSSHyIQS4xeh2qUQta2bCSfa06d3UASHDD59Q0=,tag:oU437lYIE+aST8ZyV+Zr3w==,type:str]
    VOLSYNC_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:83OBncrLeA2VjVzzJBii/mNHBwHlZtX+JIXl0U/pboimyxIB0WWiVg==,iv:J2tbt/fNUTB3TvZywnmQXLqqp87XUVAT3CvWdUiqE0I=,tag:v9hob25PkvoUZ3Lbrm5h1Q==,type:str]
    VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:H/3ryoD+DgSF/HzYzW68McFvQ21/CGTa,iv:vd2fJZk4lnvNHBLA3XKFf+DFcDgG/vL8gitIda2ITYY=,tag:z2oP8Kbd6IhTIqCosT+oEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZHVDSFNyUUpZNmpBdUNy
            WTEvdGNTVDhQUjlPQzRDQmJFelZKcGlYVVRrCnFCMVJsOGkremJLTUlyQUNpcFc1
            eVZ4eVpHMDVZV0lSRWN6ZGl2cWQwQXcKLS0tIGtzUnBGSE5LbzdUbU5nM0Fub1p4
            c1k2dWhhSElQOFFqMFIrTGtlMDZIV00Ky599xY8T3scWl4qW4n7F99g+Bb+72cZi
            +OyvyUWetprI0XeXwtv52gnZp4zGUnSoB/ikpN+HlyFPltSU3E2ffQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-18T02:21:43Z"
    mac: ENC[AES256_GCM,data:YEHxhDexpR8qsoH53sikBqh44W8hI0tYrfCRUORCel62/AFXmQ6cPRc0LlRI2FVCrHulL0GCvLbDDFBdfswH2xtMeyaCG+a4fHkAKA9PgfeVoIsnkEEidfPm0DQKjz5nWl1jdaq1mc7rndEsmMxA/ZH5xJjauptAkPG4ab+a1PA=,iv:hrB32gwTDRkIlx5uqBG+cmEzOJ4YLLCg7h3pmLSwcaE=,tag:jEw/CfZBTcGuBnD+zvqxvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
