---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-lidarr
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/lidarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: media-common
    - name: media-common-mounts
    - name: storage-rook-ceph-cluster