---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-lidarr
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/media/lidarr/app
  targetNamespace: media
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: lidarr
      VOLSYNC_CLAIM: lidarr-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom: []
  dependsOn:
    - name: media-common-resources
    - name: media-common-mounts
    - name: storage-rook-ceph-cluster
    - name: monitoring-kube-prometheus-stack-crds
