---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-common-mounts
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/common/mounts"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
