---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-sonarr
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 2m
  path: ./kubernetes/apps/media/sonarr/app
  targetNamespace: media
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  postBuild:
    substitute:
      APP: sonarr
      VOLSYNC_CLAIM: sonarr-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom: []
  dependsOn:
  - name: media-common-resources
  - name: media-common-mounts
  - name: storage-rook-ceph-cluster
  - name: monitoring-kube-prometheus-stack-crds
