---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: daemonset

    image:
      repository: ghcr.io/haveagitgat/tdarr_node_acc
      tag: 2.00.20.1

    env:
      TZ: "America/New_York"
      # PUID: "1000"
      # PGID: "1000"
      serverIP: tdarr.media.svc.cluster.local
      serverPort: 8266
      ffmpegPath: "/usr/local/bin/ffmpeg"
      nodeName:
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265

    persistence:
      media:
        enabled: true
        existingClaim: nfs-media
      cache:
        enabled: true
        existingClaim: tdarr-cache
      nvr:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/batcave-nvr/recordings
        mountPath: /nvr
        readOnly: false

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 100
      supplementalGroups:
      - 34
      - 100
      - 44
      - 226
      fsGroupChangePolicy: "OnRootMismatch"
      capabilities:
        add:
        - CHOWN

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
