---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-porla-secrets
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "false"
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/porla/secret"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-porla
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/porla/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom:
    - kind: Secret
      name: flux-porla-secret
      optional: false
  dependsOn:
  - name: networking-pod-gateway
