---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.36.0
    env:
      TZ: "American/New York"
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: 8080
          metrics:
            enabled: true
            port: 9000

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "simple-icons:zigbee"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: zigbee.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix

    securityContext:
      privileged: true

    resources:
      requests:
        cpu: 8m
        memory: 178Mi
      limits:
        memory: 256Mi

    volumeClaimTemplates:
    - name: data
      mountPath: /data
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: ceph-block

    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_516009EA-if01-port0

    nodeSelector:
      feature.node.kubernetes.io/zigbee: "true"

    envFrom:
    - configMapRef:
        name: zigbee2mqtt-config
    - secretRef:
        name: zigbee2mqtt-secret
