---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      zigbee2mqtt:
        type: statefulset

        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          nodeSelector:
            feature.node.kubernetes.io/zigbee: "true"

        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.40.1
            env:
              TZ: "American/New York"
              ZIGBEE2MQTT_DATA: /data
            envFrom:
            - configMapRef:
                name: zigbee2mqtt-config
            - secretRef:
                name: zigbee2mqtt-secret
            resources:
              requests:
                cpu: 8m
                memory: 178Mi
              limits:
                memory: 256Mi
            securityContext:
              privileged: true

    service:
      zigbee2mqtt:
        controller: zigbee2mqtt
        ports:
          http:
            port: &httpPort 8080
          metrics:
            port: &metricsPort 9000

    ingress:
      zigbee2mqtt:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "simple-icons:zigbee"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: zigbee.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: zigbee2mqtt
              port: http

    persistence:
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_516009EA-if01-port0

      data:
        existingClaim: "${VOLSYNC_CLAIM}"
