apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: ENC[AES256_GCM,data:W54=,iv:m8YKCx3rUIMiXjv80zizP6DRhfbrm4NxG+F4QARngac=,tag:oNLTzBHZMm0+SsmmFkoBdw==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:T8/00T5oitAatMhtBWj9Do97Anrw+uSTNZ7sdAQleQz9sxyZp9hoRSTTPWkb4vFWl+Ltnss8cg==,iv:KtD9e7SGTkciCHJrojMmIkz5c5v9JGLN6rRWucV8sEQ=,tag:DHWrd1hzbo0Xzj2BOTB1GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcnRlZ1RyUXQ5bGlJZmNZ
            SjlkV0pHT01BZUZVWHgzSml6OWg0cVA5YTB3ClArT2dMMnNqNVZnSjN2Tm1BQmJu
            cjUweEhDZFdGSEViUjJFY21zSEFsZVUKLS0tIFVEQmZ1Q3RaYmhCYmRZdHZqNDJk
            Y3FncklUZURzU3BOQ2lubi9aTlMra1UK3ox8/f+hKTbXfHoaS9/eEv/LmQBiYbVq
            OcLVCVTMrDBVRZ3Z/BWmHzyzKnTXnOkH1gOHosmfV+GIx3dykXdmAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-19T20:39:14Z"
    mac: ENC[AES256_GCM,data:eweQsKy7jJXEtpUKEEyLVmxw7vKbj3+4lRRnFmM7WEy4oRiym+AtW/90AhjUZfLQtXbyxE7072EBfqJL2VVIug0Lm6NERbWaHVcu3hyrH06Yabk5qKgw8FhhuHHybHp42lkHE8p0TDhLt58CEANRP5xQKDynO7Lu6ZKH3xTx5nM=,iv:8SFIHXsm1IMrC914WjHJZNAHwfxKpZJk4qsXgvDE61g=,tag:wogVVd4qKXujrpPeO+pkxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
