---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./pvc.yaml
- ./helmrelease.yaml
labels:
- pairs:
    app.kubernetes.io/name: immich-microservices
    app.kubernetes.io/instance: immich-microservices
    app.kubernetes.io/part-of: immich
