---
clusterName: ${CLUSTER_NAME}

talosVersion: v1.7.4
kubernetesVersion: 1.30.1
endpoint: "https://${CLUSTER_NAME}.${DOMAIN}:6443"

allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true

clusterPodNets:
- 172.22.0.0/16
clusterSvcNets:
- 172.23.0.0/16
cniConfig:
  name: none

additionalApiServerCertSans: &certSans
- ${CLUSTER_ENDPOINT_IP}
- ${CLUSTER_NAME}.${DOMAIN}
- "127.0.0.1" # KubePrism
additionalMachineCertSans: *certSans

nodes:

- hostname: sc1.${DOMAIN}
  disableSearchDomain: true
  ipAddress: 192.168.10.41
  controlPlane: true
  installDisk: /dev/nvme1n1
  networkInterfaces:
  - interface: eth0
    dhcp: true
    vip:
      ip: ${CLUSTER_ENDPOINT_IP}
    vlans:
    - vlanId: 4
      mtu: 1500
      dhcp: true
      dhcpOptions:
        routeMetric: 4096

- hostname: sc2.${DOMAIN}
  disableSearchDomain: true
  ipAddress: 192.168.10.42
  controlPlane: true
  installDisk: /dev/nvme1n1
  networkInterfaces:
  - interface: eth0
    dhcp: true
    vip:
      ip: ${CLUSTER_ENDPOINT_IP}
    vlans:
    - vlanId: 4
      mtu: 1500
      dhcp: true
      dhcpOptions:
        routeMetric: 4096

- hostname: sc3.${DOMAIN}
  disableSearchDomain: true
  ipAddress: 192.168.10.43
  controlPlane: true
  installDisk: /dev/nvme1n1
  networkInterfaces:
  - interface: eth0
    dhcp: true
    vip:
      ip: ${CLUSTER_ENDPOINT_IP}
    vlans:
    - vlanId: 4
      mtu: 1500
      dhcp: true
      dhcpOptions:
        routeMetric: 4096

- hostname: sc4.${DOMAIN}
  disableSearchDomain: true
  ipAddress: 192.168.10.44
  controlPlane: false
  installDisk: /dev/nvme1n1
  networkInterfaces:
  - interface: eth0
    dhcp: true
    vlans:
    - vlanId: 4
      mtu: 1500
      dhcp: true
      dhcpOptions:
        routeMetric: 4096

- hostname: sc5.${DOMAIN}
  disableSearchDomain: true
  ipAddress: 192.168.10.45
  controlPlane: false
  installDisk: /dev/nvme1n1
  networkInterfaces:
  - interface: eth0
    dhcp: true
    vlans:
    - vlanId: 4
      mtu: 1500
      dhcp: true
      dhcpOptions:
        routeMetric: 4096

controlPlane:
  schematic:
    customization:
      extraKernelArgs:
      - net.ifnames=0
      systemExtensions:
        officialExtensions:
        - siderolabs/i915-ucode
        - siderolabs/intel-ucode
        - siderolabs/iscsi-tools

  patches:
  # Configure containerd
  - &containerdPatch |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |-
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
            [plugins."io.containerd.grpc.v1.cri".containerd]
              discard_unpacked_layers = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              discard_unpacked_layers = false

  # Disable search domain everywhere
  - &disableSearchDomainPatch |-
    machine:
      network:
        disableSearchDomain: true

  # Configure kubelet
  - &kubeletConfigPatch |-
    machine:
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true
          rotate-server-certificates: true
        extraConfig:
          maxPods: 250
        nodeIP:
          validSubnets:
          - 192.168.10.0/23

  # Enable KubePrism
  - &kubeprismPatch |-
    machine:
      features:
        kubePrism:
          enabled: true
          port: 7445

  # Configure NTP
  - &ntpPatch |-
    machine:
      time:
        disabled: false
        servers:
        - ${NTP_SERVER}

  # Static host entries
  - &staticHostEntriesPatch |-
    machine:
      network:
        extraHostEntries:
        - ip: ${CLUSTER_ENDPOINT_IP}
          aliases:
          - ${CLUSTER_NAME}.${DOMAIN}

  # Custom sysctl settings
  - &customSysctlPatch |-
    machine:
      sysctls:
        fs.inotify.max_user_watches: 1048576
        fs.inotify.max_user_instances: 8192

  # Cluster configuration
  - &clusterConfigPatch |-
    cluster:
      allowSchedulingOnMasters: true
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      proxy:
        disabled: true
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0

  # ETCD configuration
  - &etcdConfigPatch |-
    cluster:
      etcd:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
        advertisedSubnets:
        - 192.168.10.0/23

  # Disable default API server admission plugins.
  - &admissionControlDisablePatch |-
    - op: remove
      path: /cluster/apiServer/admissionControl

  # Enable K8s Talos API Access
  - &talosAPIAccessPatch |-
    machine:
      features:
        kubernetesTalosAPIAccess:
          enabled: true
          allowedRoles:
          - os:admin
          allowedKubernetesNamespaces:
          - system

worker:
  patches:
  - *containerdPatch
  - *disableSearchDomainPatch
  - *kubeletConfigPatch
  - *kubeprismPatch
  - *ntpPatch
  - *staticHostEntriesPatch
  - *customSysctlPatch
  - *clusterConfigPatch
