---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal-ui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    controllers:
       ui:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: temporalio/ui
              tag: 2.31.2
            env:
              TEMPORAL_ADDRESS: temporal-server:7233
              TEMPORAL_CORS_ORIGINS: http://localhost:3000

    service:
      temporal-ui:
        controller: ui
        ports:
          http:
            port: 8080

    ingress:
      internal:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          io.cilium/lb-ipam-ips: ${SERVICE_ADDRESS_TEMPORAL_UI}
        hosts:
        - host: &host temporal.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: temporal-ui
              port: http
      # external:
      #   className: nginx
      #   annotations: {}
      #   hosts:
      #   - host: &host temporal.${EXTERNAL_DNS_3_DOMAIN}
      #     paths:
      #     - path: /
      #       pathType: Prefix
      #       service:
      #         identifier: temporal-ui
      #         port: http
