---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-tdarr
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/tdarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: media-common-mounts
  - name: storage-rook-ceph-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-tdarr-node
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/tdarr/node"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
  - name: media-tdarr
  - name: system-intel-device-plugins-gpu
