---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-immich-redis
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/web/immich/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-immich
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/web/immich/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: web-immich-redis
  - name: storage-rook-ceph-cluster
  - name: databases-cloudnative-pg
