---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: photoprism-cvd-mariadb
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.0.3-debian-11-r30
    auth:
      rootPassword: ${MARIADB_CVD_ROOT_PASSWORD}
      database: ${MARIADB_CVD_DATABASE}
      username: ${MARIADB_CVD_USERNAME}
      password: ${MARIADB_CVD_PASSWORD}
    primary:
      persistence:
        enabled: true
        existingClaim: photoprism-cvd-mariadb
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
