---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app photoprism-cvd-mariadb
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb
      version: 18.2.5
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.3.2-debian-12-r9
    auth:
      rootPassword: ${MARIADB_CVD_ROOT_PASSWORD}
      database: ${MARIADB_CVD_DATABASE}
      username: ${MARIADB_CVD_USERNAME}
      password: ${MARIADB_CVD_PASSWORD}
    primary:
      persistence:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
