---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./helmrelease.yaml
- ../../../../../templates/volsync
commonLabels:
  app.kubernetes.io/name: photoprism-cvd
  app.kubernetes.io/instance: photoprism-cvd
  app.kubernetes.io/part-of: photoprism
