apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-secret
    namespace: storage
stringData:
    client-info.yml: ENC[AES256_GCM,data:1w0Zx8w58C9K+wRngPX/kPjoHJnJc9uzGSnS0TuvQpAnrJMX8UmmecYCFFKJ3/jfxI5TX9UDmrdHNIEVqS7XtGmb3Dg+mUhODK/H7QnHsfEmxDpMFv2VqBMDcKy+DfBpdVVHJM2dcrf6G0UJtrNlyaoY,iv:5BGfJ14/Dmo2gv/0Hj4AHho8Q1Ti1cCHr0Goi8xFLcY=,tag:m1x/3RhSpMlsZhD48GreRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMVA0MlljYmNteWI5c3RI
            WG5mdFNMaGRZTHVUQTJRQnZPaldtSWRQV0dRCjN5Y1RENkRCcEU1T0x1RFcxSlUw
            VlBEbTluMFNwWWdjNFRjQTY1di9pVjQKLS0tIDhTbDVMeXJ4Y1V0c3JqL3JrNzBp
            QWFvQ2lwVzI4TTBkZEh5aXBQRjNDVzAKW95IP0sz+k1buD958/uxkEHgj/yCrgwf
            cZuX6y8zKRIh+b46souokfUTWQ9FiIOA4xT9bWWOEFvOnEwzc9PkPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T02:46:58Z"
    mac: ENC[AES256_GCM,data:cFysgft5UgE53OMYvTqJDKyyL844IPiuAgwgZ+9L8uyFfn5rPOb9zBJhVtyrzoJEMGS+/R/hF7jqolh+6O3KbaUa3TNHy1JfSbv6TUyybyAR1LkUmNMUvStslFW4TUIWlFknCarzhUaVctvCtvBEFE5MXMy8gu9mZIQiI3Waqc0=,iv:hI2neNHLa5mSMuifpALhSwnz6OIzOP77YD6fCAHc6H4=,tag:JqYIr5xwTWo5nwtEyIeWmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
