---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./wyze-bridge/ks.yaml
- ./frigate/ks.yaml
- ./deepstack/ks.yaml
- ./double-take/ks.yaml
- ./compreface/ks.yaml
