---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-cameras
  namespace: networking
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-cameras",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth0.3",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "192.168.3.0/24",
                "gw": "192.168.3.1"
              }
            ]
          }
        }, {
          "capabilities": {
            "mac": true
          },
          "type": "tuning"
        }
      ]
    }
