---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: networking
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0.4",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "192.168.4.0/22",
                "gw": "192.168.4.1"
              }
            ]
          }
        }
      ]
    }
