---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65539
              - 1030

        containers:
          *app :
            image:
              repository: ghcr.io/home-operations/lidarr
              tag: 2.12.1.4636@sha256:073c2bedb91802e116da2dd33661a32b6faf9377aec626fef623977833fdb1a2
            env:
              TZ: America/New_York
              LIDARR__INSTANCE_NAME: Lidarr
              LIDARR__PORT: &port 8686
              LIDARR__LOG_LEVEL: info
              LIDARR__ANALYTICS_ENABLED: "False"
              LIDARR__APPLICATION_URL: "https://lidarr.${EXTERNAL_DNS_1_DOMAIN}"
              LIDARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: starr-apps-secret
                    key: LIDARR_API_KEY
            resources:
              requests:
                memory: 350Mi
                cpu: 5m
              limits:
                memory: 431Mi

          exporter:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.2.0
            args:
              - lidarr
            env:
              - name: URL
                value: "http://localhost"
              - name: CONFIG
                value: "/config/config.xml"
              - name: PORT
                value: &metricsPort 9709
              - name: ENABLE_ADDITIONAL_METRICS
                value: true
              - name: ENABLE_UNKNOWN_QUEUE_ITEMS
                value: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port
            primary: true
          metrics:
            port: *metricsPort

    ingress:
      *app :
        className: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:headphones"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host lidarr.${EXTERNAL_DNS_1_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: *port

    persistence:
      media:
        existingClaim: nfs-media
        advancedMounts:
          *app :
            *app :
              - path: /media

      config:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /config

      backups:
        type: custom
        volumeSpec:
          nfs:
            server: "${SYNOLOGY_ADDRESS}"
            path: /volume1/backups/lidarr
        advancedMounts:
          *app :
            *app :
              - path: /config/backup
                readOnly: false

    serviceMonitor:
      metrics:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 10m
            scrapeTimeout: 10s
