---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name:  monitoring-kube-prometheus-stack-crds
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/kube-prometheus-stack/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-kube-prometheus-stack
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
  dependsOn:
  - name: monitoring-kube-prometheus-stack-crds
  - name: ingress-cert-manager
  - name: storage-rook-ceph-cluster
