---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./hajimari/ks.yaml
- ./vaultwarden/ks.yaml
- ./actual/ks.yaml
- ./tandoor/ks.yaml
# - ./temporal/ks.yaml
