---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-metrics-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
