apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace system
commonAnnotations:
  meta.helm.sh/release-name: &releaseName kubelet-csr-approver
  meta.helm.sh/release-namespace: *namespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
helmCharts:
  - name: kubelet-csr-approver
    repo: https://postfinance.github.io/kubelet-csr-approver
    version: 1.2.4
    releaseName: *releaseName
    namespace: *namespace
    valuesInline:
      bypassDnsResolution: true
      providerRegex: ^(sc[1-5])$
