apiVersion: v1
kind: Secret
metadata:
    name: weatherflow2mqtt-secret
stringData:
    WF_HOST: ENC[AES256_GCM,data:dDk4ljra3Q==,iv:Ljo+FSw4fQEnKriJ51fFwm4LnN8eAUTj0Oq2F8u9k00=,tag:WDqVajnbomMXt/919GDuvQ==,type:str]
    WF_PORT: ENC[AES256_GCM,data:scbSuec=,iv:/yGsWNEZGH46DIPjAOIDD1Sn6GPsel9DYDUM81LxDO4=,tag:E/2MVoBT3HUr4m9uvK/2tw==,type:str]
    MQTT_HOST: ENC[AES256_GCM,data:Bz3PKmM2f916Qkkxug==,iv:+7L8XvX7tjwfwaGAS93KaHCcfLzoZmL2+RTVpdc8bFk=,tag:eTiqyOnVkMlQwAvsALZlFw==,type:str]
    MQTT_PORT: ENC[AES256_GCM,data:Gfozng==,iv:YKISh/vGRwjQcdVUafeSxHBMsDn2xpGUBngI8Ixdqss=,tag:M1zcqBNmIMueMnduztCpXw==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:LOMTcw==,iv:9MMRSo3cigBj8c2fY/BTpNHX31ibpZSxwk11cDu71w8=,tag:KAXy0wYbENGYVBPeoVNF6g==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:MalWTvX/Zbsr1YbqpT/ugxBOl+LAh87I,iv:zTXg308rKqOT6nqJnMIrcw9NqePjm7MmzAdUVgHYPpA=,tag:ARnMpCLVgC5GWdS1G/m9FA==,type:str]
    STATION_ID: ENC[AES256_GCM,data:yLVdATM=,iv:Twe0bnKJ+iPS8hyA5gd0ciY/OW/vzvNkx7JEPwH2AJ8=,tag:wNa/xyakzex2pqx1aIO8ag==,type:str]
    STATION_TOKEN: ENC[AES256_GCM,data:X3haV7reBDEy/d/cBXa2yLt1xDTJp74hTJSuT4pzBX4AF2aW,iv:sP66Q9yDhAF01Vef2zUfgRKa2SLAVRvhJWEqLSc1H8U=,tag:o0xEURXbhNWmqXMmSxm5+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9fm6mxmshwpucy9ma2hzun0g0fnkrm2p3mhaahdnwd0p8mjqp7qzpkqnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaFBNTG5aMms4MjkzRGZp
            c1pSZlVpdHlFSUx2VEc2MEg0YkFkWUlyQ2hzCnJOZTVUZ3JTNVluN2lJZzduKzRO
            Rys5T0tveGE1ZW1lR3JTTkNpdGJVS1EKLS0tIE5MUFFiZmcwRE50UlQ4RUttZGtt
            bGQ4UVNlOWlRbURENFF0TXBWMFkzVmsK/Z7ZemO9DDe2mvkolOrSxmja3WMSWx7r
            YyMNG1zZnfS/Udpaq3BuJ0fbcBMTeKCxw/Ml1OD6s7gUCJXtZjCU6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T21:25:17Z"
    mac: ENC[AES256_GCM,data:9+GvZe0PxhoZTIpj3NWz7yNx/1pgHSCD5mLCyJE04bnnN8sIpQrFidfQvzf6XDg15NmqJnp/dSR2FbZnyWnNNknL+/SprYYvZsHZH/bzkKg5Sy5Zpu8jrS0h1NReDL5AAjBcRnpKXo0TSh9feaxsxCL7NRilLfoKUOqqVr+nOZE=,iv:qQDAXsN0pxBvG+8bB1LvJKE5MzYmFuJH0Pa2vl1u2fg=,tag:bP8VlRVMe6CxAqbx8e/YQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
