---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          memory: 200Mi
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_INTERNAL_ONLY_CIDR}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: goldilocks.${EXTERNAL_DNS_1_DOMAIN}
          paths:
          - path: /
            type: Prefix
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          memory: 200Mi
