---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvr-compreface
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/nvr/compreface/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
  - name: storage-rook-ceph-cluster
  - name: databases-cloudnative-pg
