apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-minio"
spec:
stringData:
  RESTIC_REPOSITORY: s3:http://${MINIO_S3_URL}/${VOLSYNC_S3_BUCKET_NAME}/${APP}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_S3_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_S3_SECRET_ACCESS_KEY}
