---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zooz-700-series-zwave-plus-s2
spec:
  rules:
  - # HUSBZB-01 Zwave Stick
    name: zwave
    labels:
      feature.node.kubernetes.io/zwave: "true"
    matchFeatures:
    - feature: usb.device
      matchExpressions:
        vendor: { op: In, value: ["10c4"] }
        device: { op: In, value: ["8a2a"] }
